### ISSUE TITLE
Change note color

### ISSUE THREAD

**Issue by robertsanseries** [lainsce/notejot#1]
Alterar a cor de cada nota individualmente! Poderia ser usado a opção de "seleção" já existente no sistema (quando o usuário clicar com botão direito do mouse sobre uma pasta).

![cores](https://cloud.githubusercontent.com/assets/11967501/26432760/6c60dece-40d4-11e7-948d-f78a99ee838a.png)

**Comment by lainsce** [comment]
Due to the aim of the app being to be a simple post-it app, adding colors will add unnecessary complexity.
