### ISSUE TITLE
Initial "pinned" state out of sync

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/notejot#102]
When the app first opens, the "pin" button is pressed, but the app does not stay on all workspaces. I have to toggle it off and back on to get it back.

**Comment by 4ugustin** [comment]
btw. Shouldn't be pinned state permament for particular note?

**Comment by lainsce** [comment]
Maybe making an addition to Storage, to set a bool for pinned/not pinned (true/false) in each note.

**Comment by 4ugustin** [comment]
I've just opened #106 
Please see description. Thank's for help!

**Comment by lainsce** [comment]
This is now fixed!
