### ISSUE TITLE
appdata invalid due to duplicate release, and out of sync with versions on github

### ISSUE THREAD

**Issue by decathorpe** [lainsce/notejot#103]
The latest two releases clash because they reference the same version "1.4.3" (see below).

Additionally, at least all the recent versions are completely out of sync with the versions of the github project :slightly_frowning_face:

```xml
        <release version="1.4.3" date="2018-11-23">
            <description>
                <p>Release: Desktop Notes</p>
                <ul>
                    <li>New button to stick the note to show on all workspaces and below all windows.</li>
                </ul>
            </description>
        </release>
        <release version="1.4.3" date="2018-11-09">
            <description>
                <p>Release: Font Foraging</p>
                <ul>
                    <li>Revert font decision.</li>
                    <li>Some small UI fixes.</li>
                </ul>
            </description>
        </release>
```

**Comment by lainsce** [comment]
The versions being out of sync with github is due to Houston being a bit wonky earlier this year and flubbing my Notejot releases. As for the double 1.4.3, I`ll fix it.

**Comment by decathorpe** [comment]
Thanks!

Is houston still wonky, or is something else preventing you from syncing up the version number again?

**Comment by lainsce** [comment]
Houston is not wonky anymore, so I can rewrite the appdata file to have the last version instead. :smile:
