### ISSUE TITLE
color icons not displayed in the KDE Plasma environment

### ISSUE THREAD

**Issue by sancelot** [lainsce/notejot#107]
* launching the application from Kde Plasma environment
* the colors icon are not displayed. svg files are presentin the /usr/share/icons/hicolor folder, my theme is breezedark.
* version 1.4.0 on opensuse 42.3
* screenshot
![icons not displayed](https://user-images.githubusercontent.com/122811/49932794-3fadbe00-feca-11e8-9f45-910ac92a0e7e.JPG)

**Comment by lainsce** [comment]
Notejot was not designed to be used in other desktop environments without the use of its Flatpak. Not a bug.

**Comment by sancelot** [comment]
It is possible to launch any gnome app in the KDE environment and using themes. Flatpak is not needed. However, after deep review. The problem is not related to theme icons (the svg icon for the application is used), but some issue applying the css defined theme inside the Vala Main program.

**Comment by lainsce** [comment]
Also, judging from your screenshot, you're using an older version of Notejot.
