### ISSUE TITLE
Note shouldn't be saved in .cache

### ISSUE THREAD

**Issue by jeffshee** [lainsce/notejot#114]
Hi! 

As described, note should be saved in somewhere else, perhaps `.local/share/`. Cache should be temporary files and not user data. Just a BleachBit and all my saved notes are gone. Luckily I still have some sort of backup.

Version: notejot-1.5.3-1   OS: Fedora 29

Thanks!

**Comment by lainsce** [comment]
I'll fix this soon and make a release with this fix. :+1:

**Comment by lainsce** [comment]
Fixed.
