### ISSUE TITLE
Change save file location

### ISSUE THREAD

**Issue by gibranlp** [lainsce/notejot#120]
Hi, 
This is not a current issue, but more of a request.

Is it possible to change  the save file location, to my convenience? my purpose is to sync a few computers with notes via owncloud.

I was looking already in dconf but couldn't find anything.

Thanks.

**Comment by lainsce** [comment]
Your notes save as json in a file in `~/.local/config/com.github.lainsce.notejot/` called `saved_notes.json`. This file contains everything the notes have, as color, size, contents, etc.

**Comment by Justinzobel** [comment]
I came here as I am looking for the location of where the notes are stored. I checked for that folder but it's not there. I have several notes and they're saved OK between reboots.
