### ISSUE TITLE
App automatically open a new note on every startup

### ISSUE THREAD

**Issue by MadByteDE** [lainsce/notejot#122]
**Description:**
Im used to Windows Notes Widget which automatically opened itself on startup. I want to replicated that behaviour, but when adding this Notes app to launch at startup (Elementary OS 5.0) then it automatically opens a new note alongside the existing note(s) I already created.

**Expected behaviour:**
If the app gets launched and there's an existing note, it shouldn't create a new one alongside. 

**Alternative solution:**
There could be a small icon / option to activate this "startup mode", if there are people who prefer to get a new note on every startup.

**Version:** 1.5.5

**Comment by lainsce** [comment]
Notejot wasn't made to be open at startup since it already saves your notes for every session, not needing to make it open alongside your login.

**Comment by MadByteDE** [comment]
Thanks for your reply!

That's an interesting design. Let's look at real life sticky notes. Most people use them to remember stuff, stick them on the monitor frame or something - always visible because otherwise they won't fulfill their purpose. You can say it's there on "startup". Now the real life equivalent to your design would be me, sticking a new blank note on the monitor frame everytime I boot my desktop pc. 

I respect your decision, but I truely don't understand why it is like it is, because it's such a minor tweak
to add the option for it, which makes the app usable for nearly everyone.

**Comment by MadByteDE** [comment]
Just need to add that I fixed this myself. Seemed to be a "bug" for me because the app (latest master) does not re-create a new note everytime the app starts. It just creates a new one if there's no entry in the notes list. The problem was that the saved list file contained an older entry with a blank one, which just had to be removed by hand. Now the app works as expected.
