### ISSUE TITLE
[IDEA] Sync with Google Keep or even Simplenote

### ISSUE THREAD

**Issue by aimproxy** [lainsce/notejot#126]
Hi, @lainsce I will go to propose a awesome feature, whats do you think about sync all notes with google keep or even simplenote? I learn about `libsoup` but I don't know how to do auth with `libsoup`, I could investigate if you approve this idea!

**Comment by lainsce** [comment]
It could be done with Simplenote, but not Google's Keep, since that one is a Closed API that no one has access

**Comment by aimproxy** [comment]
Wheel, There is not much interest in developing functionality for SimpleNote, as the ideal thing was to have my notes synchronized with my smartphone! :neutral_face:

**Comment by lainsce** [comment]
I'm not a mage that can simply make Keep work with Notejot, sorry!
Google still has the sync API there closed behind concrete, and we, developers, can't use it.

**Comment by saaditory** [comment]
> Wheel, There is not much interest in developing this functionality for SimpleNote, as the ideal thing was to have my notes synchronized with my smartphone!
@aimproxy 

Hey there! Just to mention here that the Simplenote app is also available for smartphones. Which can be used to view notes on mobile and makes Sync feature in Notejot more compelling. :)

**Comment by lainsce** [comment]
Pull Requests welcome! :)
