### ISSUE TITLE
[IDEA] Missing features in the toolbar

### ISSUE THREAD

**Issue by aimproxy** [lainsce/notejot#127]
Hi, it's me again, I would like add some features like
* Bold
* Italic
* Underline
* List
* Underline

Whats you think about that?

**Comment by lainsce** [comment]
I'll work on those by August. They shouldn't be difficult to implement.

**Comment by lainsce** [comment]
They are difficult to implement. I've tried without any way of doing it. The dev docs don't help me either. So... Sorry!
