### ISSUE TITLE
Change the icon when the note is pinned!

### ISSUE THREAD

**Issue by aimproxy** [lainsce/notejot#128]
Hi, when the window is pinned the icon still the same, can we change the icon? I know the only icon is this one `view-pin` but we could rotate the icon and create their one or even submit a new icon to elementaryOS team, because is hard to know if the window is pinned or note!

**Comment by lainsce** [comment]
I'll make it rotate 45 degrees in-code so it becomes a new icon. Stop by August and I'll start work on this.

**Comment by lainsce** [comment]
Fixed, rotates by 90
