### ISSUE TITLE
[IDEA] Ability to add images to a note

### ISSUE THREAD

**Issue by aimproxy** [lainsce/notejot#129]
Hi, this functionality are allready present on Microsoft Sticky Notes, check that
![](https://store-images.s-microsoft.com/image/apps.37200.13510798887395106.4d9c7397-b1e2-4e33-9e25-0c3aa7ed4fd4.db7fb800-a09d-4462-9ff5-56b782f9d602?w=1399&h=787&q=60)

I don't know if this functionality is easy to implement, but that could be cool even for Quilter!

**Comment by lainsce** [comment]
This is already in Quilter, by using the local images syntax. Check that app's Markdown cjeatsheet under the cog menu to learn how to use it.

As for Notejot, this doesn't apply as it isn't a place for image inside notes, just text.
