### ISSUE TITLE
[Request] Visual change

### ISSUE THREAD

**Issue by luizaugustomm** [lainsce/notejot#13]
Hello Lains,

Your app is awesome. Congratulations!
I have a design suggestion for you. Have you seen Nimbus (https://github.com/danrabbit/nimbus)? I think notejot would look nicer if the notes had that kind of look-and-feel.

I thought in something like that:
![mockup](http://i.imgur.com/qQ98VhY.png)

[]s
Luiz

**Comment by lainsce** [comment]
Expect this in a future release! :smile:
