### ISSUE TITLE
Use gradient overlay/undershoot when scrolling

### ISSUE THREAD

**Issue by jlnr** [lainsce/notejot#130]
Right now the main area of the note gets clipped when it is long enough to need vertical scrolling:

![Notejot](https://user-images.githubusercontent.com/70772/61629380-f7872300-ac84-11e9-9806-7aef3ecba7f6.png)

What do you think about adding undershoot gradients as [in some newer system scroll views](https://github.com/elementary/stylesheet/pull/522)?

**Comment by lainsce** [comment]
Fixed
