### ISSUE TITLE
Viewport does not scroll all the way to the end when using the keyboard

### ISSUE THREAD

**Issue by jlnr** [lainsce/notejot#136]
This is a follow-up issue to #130 in Notejot 1.5.8. (Thanks for adding the undershoot so swiftly :+1:)

When using arrow keys or Ctrl+Home/Ctrl+End to move to the start/end of a long note, there is still undershoot because the viewport does not move all the way. Only the mouse wheel can reach the minimum and maximum viewport.

Expected behavior: Moving the cursor with the keyboard also completely reveals the top and bottom of the note.

**Comment by lainsce** [comment]
This may be a GTK issue. I have no code that would impede anyone from reaching the end of a note. :disappointed:
