### ISSUE TITLE
contents of second note lost after minimize

### ISSUE THREAD

**Issue by monoid14** [lainsce/notejot#137]
1. create a note
2. create a second note
3. close the secone note by clicking the X on the window (first note remains open)
4. minimize the first note by clicking the notejot icon on the plank (important step - seems to cause the problem)
5. click again the notejot icon to restore the first note
6. close the first note by clicking the X on the window (the application terminates)
7. open again application by clicking the notejot icon in Applications
8. the two notes appear, but the second note is empty - its content is lost!

**Comment by lainsce** [comment]
Are you using the flatpak or the AppCenter version? This sounds like an old bug that was fixed long ago.

**Comment by monoid14** [comment]
I installed through the appCenter a couple of months ago, not sure what
version it is. I just hope this info is useful for you, if it is a known
issue then all well!

**Comment by lainsce** [comment]
Closing the bug as it is a fixed bug from before:
#50.
