### ISSUE TITLE
Button icons are hard to see when using a dark theme

### ISSUE THREAD

**Issue by amivaleo** [lainsce/notejot#140]
Hi!

If you use a dark theme, even if that is the dark variant of Adwaita in gnome, the button icons can be hard to read, especially with some note backgroud colours.

For example:

![Schermata da 2019-09-17 09-35-42](https://user-images.githubusercontent.com/24316547/65021177-e67a2b80-d92e-11e9-9f38-a5fec70d31d8.png)

**Comment by lainsce** [comment]
That's on the Adwaita theme, the buttons there don't have a flat variant without a background. Not a bug with the elementary theme.
