### ISSUE TITLE
Pinned can't be brought to focus above other desktop windows.

### ISSUE THREAD

**Issue by Julioevm** [lainsce/notejot#144]
Hi,

I was wondering if the behavior of the pinning is correct.
If I pin a note, it stays down behind every window and I cant bring it back up if I click the notejot icon on the dock, meaning the only way for me to see it is to minimize everything, I don't see much benefit on this functionality. Almost the same as leaving it unpinned.
To me, at least, what I look for in pinning something is to leave it always visible; above all other windows.
Thanks!

**Comment by lainsce** [comment]
Pinning will make it so that the window is shown on every workspace instead of only on one.
