### ISSUE TITLE
Note content lost bug

### ISSUE THREAD

**Issue by xooler** [lainsce/notejot#149]
Hi. Thank you for app. I found big problem in work with multiple notes. Version 1.6.0.

I found same issues, but problem saved on last elementary appcenter version.

Video demonstration: https://yadi.sk/i/oaClVGKJba0zlw

I think problem is here - https://github.com/lainsce/notejot/blob/d89691fa1d80dbf4b973b0606e07136d9a9b696b/src/Application.vala#L95
To save notes to storage you sorting through open notes windows. In video i close one of window and it lost content, but window info like position and title was saved.

Sorry for lost important note =(

**Comment by lainsce** [comment]
I'm going to look at it and fix it soon.

**Comment by lainsce** [comment]
After thinking about it, maybe it's the update being outside the checking for windows that is the problem in that code, when I get internet back, I'll fix this.

**Comment by lainsce** [comment]
Fixed in next version.
