### ISSUE TITLE
Can't make notes smaller

### ISSUE THREAD

**Issue by jod82** [lainsce/notejot#150]
Version 1.6.0

I can't resize the notes to make them smaller. I can make them bigger but not shrink them past their original size. It's a waste of space if I have a ,for example, 2 line note. 
Thanks!

**Comment by lainsce** [comment]
The size can't go smaller due to standardization of window size to an actual Post-It™ note.
It's just the design of Notejot. It doesn't hurt if the contents don't use all of it?
