### ISSUE TITLE
Provide both a close and a trash button

### ISSUE THREAD

**Issue by rwoolf** [lainsce/notejot#151]
You presently only have a trash button in the top left corner.  It would be nice if you put a close X button, with the trash next to it.  The behavior would be that if you select the close, it would perform the same as if you right click on the app in the Dock and select "close."  Whereas the trash would continue to do as it does and delete the note.  I often like to close down my notes so having a close right on the sticky note would be easier than having to go down to the Dock to do it.

**Comment by lainsce** [comment]
The thing is, it used to have that, but people started losing their notes's contents using it... :pensive:

**Comment by yeboahnanaosei** [comment]
But @lainsce clicking the trash icon deletes the note altogether meaning I lose the contents of my notes. I just want to close the app and return to it later with the contents still intact.

It feels a bit painful to require two clicks to "close" the app. Something we all do with one click with virually every app.
Software is supposed to be familiar. And what is more familiar than having an "x" icon to close an app.

My suggestion is to please place the "x" close button where we all expect it to be at the top left and rather place the trash icon in the settings popup.

This way it will require us the users to explicitly go there to delete the note. If a user will go into the settings popup to click the delete icon, then it probably suggests that the user indeed really wants to delete the note.

**Comment by lainsce** [comment]
When I had the close button it explicitly had a bug that would kill a note's contents even if that's not what was meant. That's what I'm trying go avoid happening. I also don't like to hide it, but for the time being while I find a way to remedy this, the UI will just have to be like this 😭

**Comment by yeboahnanaosei** [comment]
Really? I'm a bit surprised because I use Notejot and never experienced what you are describing. I freely closed and reopened the notes with my contents intact. I would have loved to help but Vala is what is holding me back.

**Comment by lainsce** [comment]
Notejot is being rewritten from the ground up and will be released as soon as Hera+1 (The next OS release) is up due to using newer technologies. Hang tight, but if you're adventurous, feel free to test it out by going on the existing single Pull Request before it is even merged into the main branch. Just have to hunt down the new libraries yourself.
It'll also fix this bug.
