### ISSUE TITLE
[notejot-next] A thinner titlebar similar to the elementary Terminal

### ISSUE THREAD

**Issue by hanaral** [lainsce/notejot#161]
I love the new look of the app, and how well it fits in with the new Odin stylesheet. Since there are only 3 buttons on the titlebar, I think it would fit the notepad aesthetic more to have the titlebar be the same size as elementary Terminal's (From what I gather, this would be the 'elementary' way).

**Comment by lainsce** [comment]
You know, you do have a point.
In actuality, the sizing I added to them was to make the titlebar easier to drag around. It's, believe it or not, smaller than the default size of titlebars in elementary. But with the popped-out notes from the main window, I chose to have smaller titles just as you suggest.

**Comment by hanaral** [comment]
Cheers for the reply, I see why they are a bit larger now.
