### ISSUE TITLE
Feature: Confirm before deleting notes + Trash View

### ISSUE THREAD

**Issue by pickybl2020** [lainsce/notejot#162]
Quite often I find myself accidentally deleting notes because the "ctrl + w" shortcut while having notejot in focus while thinking I have another.
despite being quite useful it defeats its purpose when this happens because there's no way recovering those lost by mistake notes which some of them might take quite a lot of time to write..

please provide either
an option to change the keyboard shortcut
or a confirmation dialog
or an option to toggle the ability for the note to undeletable until the user decides later otherwise.

id like to congratulate you for this very useful app

**Comment by lainsce** [comment]
I am adding such a thing to the notejot-next branch :)

In there, I'm working towards a dialog that confirms/cancels the deletion.

**Comment by pickybl2020** [comment]
excellent! thank you!

how about a temporary "trash"  folder as well?

**Comment by lainsce** [comment]
A Trash folder... I think that's doable, but would add some complexity :P

**Comment by lainsce** [comment]
Fixed in #153, closing.
