### ISSUE TITLE
[Notejot-next] Unify the rounder corner radius with other elementary apps

### ISSUE THREAD

**Issue by hanaral** [lainsce/notejot#166]
I thought something was a bit off about the corners, so I checked them against the system settings app and this is what I found:
![Screenshot from 2020-09-15 13-17-25](https://user-images.githubusercontent.com/58219504/93209457-12a0d600-f756-11ea-8b23-fce101cd60d4.png)
I'm not sure what the official corner radius is, but it looks like its already really close.

**Comment by lainsce** [comment]
Notejot Next uses the solo Design System on top of elementary's HIG. The different radius is on purpose.

Check [https://lainsce.us/src/solo](here) for details.
