### ISSUE TITLE
Styling buttons affect different instances of same string

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#168]
In notes with multiple occurrences of the same string applying styling to one of the later occurences always applies it to the first one instead.

1. Select last occurrence of string in note
![image](https://user-images.githubusercontent.com/1908896/105851477-6e704b00-5fe3-11eb-8feb-f286764419d5.png)

2. Click "bold" button
![image](https://user-images.githubusercontent.com/1908896/105851496-74fec280-5fe3-11eb-8a1c-90e1bc41e983.png)

3. First occurrence is bold

I'm using Fedora 33, and v2.5.0 from Flathub.

**Comment by lainsce** [comment]
I'll look into this.

**Comment by lainsce** [comment]
Fixed. :)
