### ISSUE TITLE
Color chooser: Focus border is not rounded 

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#169]
The color chooser dots have a rectangular focus border, which looks a bit glitchy:

![image](https://user-images.githubusercontent.com/1908896/105851928-0a9a5200-5fe4-11eb-88ff-66b1b57bd04d.png)

IIRC there's a special CSS selector for the focus border, but I don't remember which one it was. I'd probably look at what the `circular` class in Adwaita does.

**Comment by lainsce** [comment]
I'll look into this.

**Comment by lainsce** [comment]
Fixed. :)
