### ISSUE TITLE
GtkHeaderBar box-shadow

### ISSUE THREAD

**Issue by rokf** [lainsce/notejot#17]
I suggest that you add the `box-shadow` property to the header's CSS. It will remove the annoying `1px` white line between the header and the body.

I've tried `box-shadow: none;` and `box-shadow: inset 0px 1px 2px -2px white;` in some of my apps. The second one looks better tho :wink:.

**Comment by lainsce** [comment]
Thanks for the tip! 👍 
Will be featured in a new release soon!
