### ISSUE TITLE
Bringing/keeping window on top

### ISSUE THREAD

**Issue by GitDwig** [lainsce/notejot#170]
## Hello! If you found an error in this app, follow this template:

Title: Bringing/keeping a window on top
Comment: I didn't "ask" for Notejot; it showed up during a Ubuntu update.

Issue,: Create a window, then move it "over" another window; it "slides behind" the other one.  Even if you leave part of the window visible, clicking on it doesn't raise it.  Clicking on the Notejot icon in Favorites does nothing.

Also, when first clicking on the icon in Favorites, several windows are created.

Not so much a bug as a limitation: it seems not to be able to resize the window.

*
* State what version you're using
1/26/2021: Not sure; no details were available.  

The above aside, I like what I've seen of Notejot.  If this is just a matter of a buggy early release, I'll be patient with it.  

Thanks!

**Comment by lainsce** [comment]
This doesn't sound like the behavior of Notejot. It should always be acting like a normal window. Can you show me screenshots of this happening?
