### ISSUE TITLE
Brining/keeping window on top (#170)

### ISSUE THREAD

**Issue by GitDwig** [lainsce/notejot#171]
This is a reply to the author's reply of 8:23PM today.
As you can see from the screenshot, there are 
![Screenshot from 2021-01-26 20-35-48](https://user-images.githubusercontent.com/78061585/105945105-76e37880-6019-11eb-8d9d-8047afe833f3.png)
some blank windows with "Notejot" at the top.  In the left bar, the 4 dots are next to the Notejot icon.

Please, I'm not trying to be difficult, but I thought you'd appreciate knowing what's happening on a potential user's computer.

**Comment by lainsce** [comment]
Ah, this is the old version of Notejot, not the new one.

Please download the new version at: https://flathub.org/apps/details/io.github.lainsce.Notejot

Sorry if I was rude in some way.

**Comment by lainsce** [comment]
Did this help you?

**Comment by lainsce** [comment]
Well, I'll assume the silence is confirmation that it helped. :wink: 

Closing...

**Comment by GitDwig** [comment]
I haven't had a chance to try it; I'll get to it in the next day or so, 
and I'll let you know how it goes.

Thanks for a promising app,
Don
