### ISSUE TITLE
Color chooser popover spacing

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#172]
The vertical and horizontal padding in this popover is uneven (more padding on the left/right than above the color circles, and not enough below). I'd suggest reducing the width of the dialog such that the padding on top corresponds to that at the sides, and increasing the margin below them.

![image](https://user-images.githubusercontent.com/1908896/106526061-3f773f00-64e5-11eb-8eac-430dae7cd2dc.png)

**Comment by lainsce** [comment]
Does this look better or worse?

![a](https://user-images.githubusercontent.com/4886639/106533209-798a1600-64d0-11eb-8d4e-e71e3453a65b.png)

**Comment by lainsce** [comment]
I'm going with B as it looks more layoutted correctly.
