### ISSUE TITLE
Primary and secondary menu are gone in the latest version

### ISSUE THREAD

**Issue by BrainBlasted** [lainsce/notejot#173]
Title. The latest version published on Flathub is missing both menus now. See:

![image](https://user-images.githubusercontent.com/29347290/106533127-68c4aa80-64a6-11eb-8a79-66d798524f7e.png)

**Comment by lainsce** [comment]
Wait, how did this happen?

Both menus are menu models in .ui files now and they are gresourced and they're in this repo.

I'm confused.

**Comment by BrainBlasted** [comment]
Looks like this only happens on first launch/when you launch with no notes.

**Comment by lainsce** [comment]
I know that I've set the secondary menu to only show if there's an open note, but the main menu I left intact visible at all times.

**Comment by lainsce** [comment]
OK, I found the culprit, and fixed it. Closing. :)
