### ISSUE TITLE
Color chooser active state

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#174]
Currently the active color is indicated by a 1px blue border, which is a bit hard to see. I'd suggest increasing it to 2px, that's what other apps (e.g. Apostrophe) do in similar cases.

![image](https://user-images.githubusercontent.com/1908896/106605013-b4d42580-6560-11eb-85c4-4cfaa5d17022.png)

**Comment by lainsce** [comment]
Actually these shouldn't be bordered when active, and the colors are a choice, not a state.

**Comment by lainsce** [comment]
Fixed :)
