### ISSUE TITLE
Color chooser: active state on wrong color

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#175]
The color of the currently active note is not correctly indicated in the popover (here it should be purple, but it's green):

![Screenshot from 2021-02-02 14-15-25](https://user-images.githubusercontent.com/1908896/106605571-565b7700-6561-11eb-91dc-24b772a8aa9f.png)

Fedora 33, installed from Flathub

**Comment by lainsce** [comment]
I think it's just me forgetting to set everyone of those as "inactivatable" via styling, since there's not really a reason to make one of them active as it's a choice, not a state.

**Comment by lainsce** [comment]
Fixed :)
