### ISSUE TITLE
Update version on AppCenter for elementary OS

### ISSUE THREAD

**Issue by Trapavko** [lainsce/notejot#176]
Hello! AppCenter for elementary OS has version 1.6.3 listed. I've been using it for a while but has multiple bugs relating to always-on-top and showing on wrong windows. I've decided to file a bug report but discovered that this is an old version (from one of the closed issues).

Problem is AppCenter is outdated version and still references this page for _**Report a problem**_.

![image](https://user-images.githubusercontent.com/50308257/106821632-87b07180-664b-11eb-8da5-812863d22a57.png)

![image](https://user-images.githubusercontent.com/50308257/106821668-97c85100-664b-11eb-964f-b0344eaa0373.png)

It would be a good idea to bump the version on AppCenter notifying users to use flatpak version.

**Comment by lainsce** [comment]
Thing is, I can't publish on AppCenter anymore because the dashboard used to publish apps for review is sort of broken, and I can't do anything.

I guess I'll pin this issue so that people understand when coming from AppCenter.
