### ISSUE TITLE
doesn't save

### ISSUE THREAD

**Issue by ifiraso** [lainsce/notejot#177]
as title says it doesn't save when u exit the program the texts other than the title gets deleted .
the app is really perfect and i like everything just fix it please .

Thanks!

**Comment by lainsce** [comment]
Could you give me more info on how it happened?

**Comment by fastrizwaan** [comment]
Create a note, Close app, reopen the note, add some text at the end, and click 'x' (close); restart app, the note will not have the last added text.

**Comment by lainsce** [comment]
I see, will fix this.

**Comment by lainsce** [comment]
Fixed.
