### ISSUE TITLE
New Note should suffix <number>, instead of just "New Note"

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#178]
Using flatpak version.

Please suffix Number to "

Current
![Screenshot from 2021-02-11 05-11-26](https://user-images.githubusercontent.com/1161682/107587361-a3a5ab80-6c27-11eb-9a6e-43563ecc8b3c.png)

Expected:
![Screenshot from 2021-02-11 05-12-52](https://user-images.githubusercontent.com/1161682/107587450-ccc63c00-6c27-11eb-9a00-d2bd6764cd24.png)

**Comment by lainsce** [comment]
I'll implement this. :)

**Comment by lainsce** [comment]
Done
