### ISSUE TITLE
Please add "Bullet" and "Numbered List" and "task list"/to-do

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#179]
Notes need Bullet list (*) and Numbered list

- bullet 1
- bullet 2

1. numbered 1
2. numbered 2

https://stackoverflow.com/questions/3923436/writing-bullets-and-number-text-gtktextview

This is really needed for Todo inside notes
- [ ] task list 1
- [ ] task list 2
- [ ] task list 3
![](https://wiki.gnome.org/Projects/Vala/GTKSample?action=AttachFile&do=get&target=treeview-listsample.png)

https://wiki.gnome.org/Projects/Vala/GTKSample#TreeView_with_CellRendererToggle

**Comment by lainsce** [comment]
I can do the bulleted lists and the numbered lists, but the checkboxes I can't because it's not that simple to implement this in a way that can be saved reliably.

**Comment by lainsce** [comment]
Fixed.
