### ISSUE TITLE
Please give colors to New Notes automatically

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#180]
Plain colors are bland, if we could give colors on Note Creation, that would make it more appealing.

![Screenshot from 2021-02-11 05-25-49](https://user-images.githubusercontent.com/1161682/107588414-a30e1480-6c29-11eb-9054-246a9d54b464.png)

![Screenshot from 2021-02-11 05-24-15](https://user-images.githubusercontent.com/1161682/107588345-8245bf00-6c29-11eb-99d2-ace8244bedde.png)

**Comment by lainsce** [comment]
I purposefully made it this way so you choose the color yourself and not me the dev :P
