### ISSUE TITLE
New Note (ctrl+n) does not accept input

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#181]
On creating new note with + on toolbar or ctrl+n shortcut, typing anything does not get into the note Title.

Example:
1. Ctrl+N
2. typing should create note title/header
3. pressing tab or enter should switch to subtitle
4. again pressing tab or enter key should move the text entry to text view.
5. in the text view pressing tab should be normal tab.

this will be quicker to create a note.

**Comment by lainsce** [comment]
Good idea, I'll implement this :)

**Comment by lainsce** [comment]
I can't do this due to the nature of the title & subtitle widgets, as it's a label, not an entry by default.

Sorry, but I'll have to close this as invalid.

**Comment by fastrizwaan** [comment]
Ok, why not give TextView immediate focus?

**Comment by lainsce** [comment]
It should already be the focus, unless something got broken.

**Comment by lainsce** [comment]
I checked, and it wasn't, but now it is. I just need to fix the other issue and then it'll be all done to release.
