### ISSUE TITLE
ctrl+n keeps creating notes

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#183]
(io.github.lainsce.Notejot:26139): Handy-CRITICAL **: 07:40:34.110: hdy_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed

(io.github.lainsce.Notejot:26139): Handy-CRITICAL **: 07:40:34.563: hdy_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
![ctrl+n bug](https://user-images.githubusercontent.com/1161682/107723006-269d3380-6d06-11eb-93d0-898727635f3b.gif)

**Comment by lainsce** [comment]
> (io.github.lainsce.Notejot:26139): Handy-CRITICAL **: 07:40:34.110: hdy_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
> (io.github.lainsce.Notejot:26139): Handy-CRITICAL **: 07:40:34.563: hdy_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed

You can ignore these, they're just the button with three-dots being applied to the headerbar, too fast due to pressing Ctrl+N and holding.
It's not a bug.

**Comment by fastrizwaan** [comment]
It's only single Ctrl+N press and NO HOLDING!

**Comment by fastrizwaan** [comment]
How to reproduce (git version):
1. Launch Notejot, or click on any existing New Note on sidebar
2. press ctrl+N
3. bug manifests

**Comment by lainsce** [comment]
It should work on git version. No need to yell at me.
