### ISSUE TITLE
Clicking on formatting button, does not allow typing

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#184]
Clicking on the formatting button steals the focus away from TextView.

![formatting bug](https://user-images.githubusercontent.com/1161682/107723414-120d6b00-6d07-11eb-8d33-0efe88e2d321.gif)

**Comment by lainsce** [comment]
That's because they need something selected in the textview to work

I think what's missing is after clicking, giving the focus back to the textview.

**Comment by lainsce** [comment]
Fixed!
