### ISSUE TITLE
Text color in dark variant

### ISSUE THREAD

**Issue by zoncrd** [lainsce/notejot#19]
Enabling dark theme with elementary tweaks the text color of the note's body it's quite unreadable
![screenshot from 2017-06-05 17 40 20](https://cloud.githubusercontent.com/assets/6806779/26791202/98653466-4a16-11e7-996c-d38e2c9bd8d7.png)

compared with the light theme

![screenshot from 2017-06-05 17 39 46](https://cloud.githubusercontent.com/assets/6806779/26791250/c00a828c-4a16-11e7-8ac6-fc1f8cb314dc.png)

**Comment by lainsce** [comment]
Marking this as WontFix because using Tweaks is already a sign that you know what will happen to your system when changing it with Tweaks.
