### ISSUE TITLE
Avoid prominent placeholder subtitles

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#190]
It's a bit weird to have to come up with a subtitle for everything, because it doesn't really make sense for every note (e.g. what's the subtitle to a shopping list or random set of terminal commands?). However, if you don't edit the default subtitles you're left with a sidebar full of items with "Note Subtitle". Because of the very distinct styling in the header, the placeholder also doesn't look great in the header.

Perhaps subtitles could be made optional? When there is no subtile the first line of the note could be used as subtitle in the sidebar, and the very prominent "Note Subtitle" could be replaced with something more discrete, e.g. a dimmed "Add Subtitle" label styled like regular text (i.e. not bold or a larger size).

**Comment by lainsce** [comment]
What if the subtitle was the date of creation of the note instead? Would that work?
Also, it wouldn't be editable this way, but permanent..

**Comment by lainsce** [comment]
![notejot](https://user-images.githubusercontent.com/4886639/107859350-b8489600-6e17-11eb-8926-81cb14546b6e.png)

Like this. How's it?

**Comment by lainsce** [comment]
Fixed.

**Comment by bertob** [comment]
> What if the subtitle was the date of creation of the note instead? Would that work?

I think so, but I'd use a relative timestamp (e.g. "2 hours ago", "yesterday", "October 2020") and only show the precise date/time on hover. It might also be interesting to have a "last edited" timestamp, but not sure where that would go UI-wise :thinking:

**Comment by lainsce** [comment]
> I'd use a relative timestamp (e.g. "2 hours ago", "yesterday", "October 2020")

There was a thing on elementary's Granite that had this functionality, and it's a lot of code to recreate :(

**Comment by lainsce** [comment]
Looks like this when ported and used:
![bopeebo](https://user-images.githubusercontent.com/4886639/107867991-ddacc280-6e5e-11eb-9b81-23252aa06566.png)

**Comment by bertob** [comment]
> There was a thing on elementary's Granite that had this functionality, I'll just port it over

I think GLib even has something like that built in, maybe ask in #libhandy or #gnome-hackers

> Looks like this when ported and used:

Looks good. I assume you'd still change it in the sidebar to match the one in the view?

**Comment by lainsce** [comment]
> Looks good. I assume you'd still change it in the sidebar to match the one in the view?

In the sidebar, I'm thinking of showing the exact date for organization purposes. Makes more
sense when you consider the folded view, the list of notes being sorted by recency as I'm doing
would render the relative time useless in the list, as the most recent note is always at the top,
and would show "Now" which isn't nice UX wise to show in a list.

**Comment by bertob** [comment]
I don't know, that's what other notes apps seem to do:

![image](https://user-images.githubusercontent.com/1908896/107881815-40956c80-6ee6-11eb-856e-26fc419f4f13.png)

**Comment by lainsce** [comment]
That's not relative time. :stuck_out_tongue: 
That's just the hour:minute when the note was made, plus first line of the doc. :thinking:

**Comment by lainsce** [comment]
What Apple does there is:

- Is it today? Show time.
- Is it yesterday and before? Show date.

**Comment by bertob** [comment]
> That's not relative time. stuck_out_tongue

Ah, true :D 

But in our case we're not showing the first line of the note, so we'd have the space I think. That said, no strong opinion here. Absolute time would work too as long as it's kept compact, like in the Apple case.

**Comment by lainsce** [comment]
Made it so the first line is there, so now it looks more like the Apple example, but
it's more like this:

**This is awesome** :tada: 
16:35 · No more paper backgr...
