### ISSUE TITLE
Tone down subtitle styling

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#191]
Large, bold type works well for the note titles, but subtitles don't need to be quite so prominent. The top section background is sufficient to visually separate the header section from the actual note content, so I think it'd look nicer if the subtitle wasn't both bold and larger than regular text.

**Comment by lainsce** [comment]
![notejot](https://user-images.githubusercontent.com/4886639/107859350-b8489600-6e17-11eb-8926-81cb14546b6e.png)

How about this?

**Comment by lainsce** [comment]
Fixed.
