### ISSUE TITLE
Increase spacing between lines

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#192]
The spacing between lines is a bit tight, making the text feel cramped, I'd increase it a bit:

![image](https://user-images.githubusercontent.com/1908896/107856674-01094a80-6e2a-11eb-8422-f94216cf943d.png)

For some background reading on the ideal line spacing, see https://practicaltypography.com/line-spacing.html

**Comment by lainsce** [comment]
![notejot](https://user-images.githubusercontent.com/4886639/107859350-b8489600-6e17-11eb-8926-81cb14546b6e.png)

How about this?

**Comment by lainsce** [comment]
Fixed.
