### ISSUE TITLE
More padding on the left than on the right side

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#193]
There is a substantial amount of padding on the left side of the notes view, but almost none on the right side:

![image](https://user-images.githubusercontent.com/1908896/107856736-83920a00-6e2a-11eb-800c-52d0c98162e9.png)

Obivously it would be nicer if both were the same :)

It would also be good to wrap the entire content column in an HdyClamp, in order to have a maximum width that keeps the text legible when the app is maximized.

**Comment by lainsce** [comment]
![notejot](https://user-images.githubusercontent.com/4886639/107859350-b8489600-6e17-11eb-8926-81cb14546b6e.png)

How about this?

**Comment by lainsce** [comment]
Fixed.
