### ISSUE TITLE
Mismatch between header color and sidebar dot color

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#194]
I've noticed that sometimes the color in the sidebar does not match the one in the actual note: 

![image](https://user-images.githubusercontent.com/1908896/107856870-7cb7c700-6e2b-11eb-8c2d-d8a2ff3ee86f.png)

Not quite sure how to reproduce, but they seem to always revert to white in the sidebar.

**Comment by lainsce** [comment]
That's strange. What steps do you think poroduce this result?

**Comment by lainsce** [comment]
I found the steps:

- Make three notes
- Put colors on them
- Move to trash the second from the list
- The second note's color will now be the first note's color, but the third note keeps theirs.

**Comment by lainsce** [comment]
Fixed this by using list models :)
