### ISSUE TITLE
Sort notes by most recently edited

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#195]
Currently the notes are always sorted by creation time, which doesn't really scale. I'd change it to most recently edited instead.

**Comment by lainsce** [comment]
IIRC, they're sorted by name right now, e.g. a note with A as the first letter will be sorted first than a note with Z as first letter, and so on.

I'll sort them by the subtitle, which is the time, and make it by recency of the timestamp.

**Comment by lainsce** [comment]
Fixed!
