### ISSUE TITLE
check list for Todo / Tasks

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#197]
![](https://zim-wiki.org/screenshots/zim-tasklist.png)

Zim is a python gtk3 program, it does have check box list which helps a lot for Todo Tasks.

Please consider adding Check box List.
https://zim-wiki.org/index.html

**Comment by lainsce** [comment]
Zim uses a highly custom markup than HTML to have those checkboxes, I'm closing as out of scope for Notejot.
