### ISSUE TITLE
Ability to open notes disappeared

### ISSUE THREAD

**Issue by yerbestpal** [lainsce/notejot#20]
Not sure if I'm loosing my mind or not but I could have sworn there was an ability to open and save notes until recently. Correct me if I'm wrong, but I thought that was pretty essential stuff.

**Comment by lainsce** [comment]
Don't worry, your notes are safe! Just open them with Quilter or your text editor of choice, Notejot is now an applet for quick temporary notes, as you would do with sticky notes in the real world, with the 1.0.9 update.
