### ISSUE TITLE
No border below search bar

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#200]
The new search bar needs a border at the bottom:

![image](https://user-images.githubusercontent.com/1908896/108544560-ef6ee980-72e6-11eb-945f-6baebfde97c5.png)

**Comment by lainsce** [comment]
:facepalm: I knew I missed something. I have to color the bg in the list below to match the bg around the searchbar, not a border

What css class is it?

**Comment by lainsce** [comment]
I fixed it. :)
