### ISSUE TITLE
No font size option is active

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#201]
In any group of radio buttons, one of them should always be active to indicate the current state. After starting the app none of the font size ones are active for me:

![image](https://user-images.githubusercontent.com/1908896/108544923-6d32f500-72e7-11eb-8ff1-d61f8d646198.png)

**Comment by lainsce** [comment]
![hmm](https://user-images.githubusercontent.com/4886639/108548094-1cf96a00-72ca-11eb-9311-3fce8800777a.png)

Not doubting you, but in here, it is selected at startup.

**Comment by lainsce** [comment]
I'll look into this further.

**Comment by rafaelmardojai** [comment]
It only happens with a fresh installation.

**Comment by lainsce** [comment]
Oh, so it's probably not seeing the default. Easy fix then.

**Comment by lainsce** [comment]
Fixed!
