### ISSUE TITLE
sub text is in HTML

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#207]
![text_error](https://user-images.githubusercontent.com/1161682/109021521-f6c83580-76e0-11eb-8018-f028c3139db0.png)

Just typing any text make the sub text in the note to html code

**Comment by lainsce** [comment]
Yes this is due to the notes content being HTML, and the widget using plaintext by default. I'm looking for a solution to this.

**Comment by fastrizwaan** [comment]
You could either do Tag Stripping https://stackoverflow.com/questions/286813/how-do-you-convert-html-to-plain-text or convert html2text

**Comment by lainsce** [comment]
Fixed!
