### ISSUE TITLE
Please use Toggle buttons  for Formatting buttons

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#209]
https://valadoc.org/gtk+-3.0/Gtk.ToggleButton.html
![Screenshot from 2021-02-24 20-52-12](https://user-images.githubusercontent.com/1161682/109022953-583cd400-76e2-11eb-9e66-117dd0d9be1c.png)
![togggle](https://user-images.githubusercontent.com/1161682/109022961-5a9f2e00-76e2-11eb-9c0b-826ebbc8a0ce.png)

**Comment by lainsce** [comment]
They are different from the example, because they are supposed to be pressed after you select text, not "activate a mode" like in LibreOffice.

Not a bug.
