### ISSUE TITLE
Search searches note titles as that's what is more important in the sidebar.

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/notejot#212]
Search searches note titles as that's what is more important in the sidebar.
It's by design.

Note contents are secondary, and aren't the focus of the search.

_Originally posted by @lainsce in https://github.com/lainsce/notejot/issues/210#issuecomment-785312640_

You could see that Search does not search the title "Physical Health".

**Comment by lainsce** [comment]
Yeah, now that's a bug I overlooked it, sorry! :/

**Comment by lainsce** [comment]
Fixed!
