### ISSUE TITLE
Translations are not completely applied

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/notejot#213]
Hi! I've just build Notejot from master to check the translations I made a few days back and most of the lines are not being translated even if they are. Here are some examples:

![notejot1](https://user-images.githubusercontent.com/42654671/109143426-edc67b00-7757-11eb-8389-f5f0b1b37686.png)
![notejot2](https://user-images.githubusercontent.com/42654671/109143429-ee5f1180-7757-11eb-84db-a52938c68ea1.png)
![notejot3](https://user-images.githubusercontent.com/42654671/109143430-ee5f1180-7757-11eb-8062-67b20f87c6a6.png)
![notejot4](https://user-images.githubusercontent.com/42654671/109143436-eef7a800-7757-11eb-9827-7d95aa3effa3.png)

**Comment by lainsce** [comment]
Sorry, I have to make a release for the translations to be pushed, and as you can see by the other issues, I working on those before I do a release. :sweat_smile:

**Comment by oscfdezdz** [comment]
Oh, I didn't know that a release is needed to push the translations, sorry. Thanks for your work, closing this then.
