### ISSUE TITLE
Sidebar items scroll into nothingness

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#219]
The sidebar has a searchbar that looks inline, but is actually in a fixed position at the top. This means that when you scroll, the content is cut off at an invisible barrier:

![image](https://user-images.githubusercontent.com/1908896/109566841-bbfd3d80-7ae4-11eb-9ea5-1709d6ca7989.png)

Potential solutions:
1. Make the search bar inline (i.e. scroll with the content)
2. Add a bottom border to the search bar container
3. Hide the search bar by default, and reveal it using a button the headerbar (like in e.g. GNOME Settings)

**Comment by lainsce** [comment]
I'll go with 3, which will even help make the notes sidebar be more spacious I guess as well. Getting two birds in one stone.

**Comment by lainsce** [comment]
![a](https://user-images.githubusercontent.com/4886639/109592384-f15a5900-7aed-11eb-8b59-f1d28428b950.png)

Fixed :)
