### ISSUE TITLE
No issue: short question about page0 and page1

### ISSUE THREAD

**Issue by Etamuk** [lainsce/notejot#221]
Hello!

I have almost finished revision of my latest German translation. 
But I cannot find the words  page0 and page1 in the UI (version 2.7.0 flatpak). Can you explain it to me? Or shouldn´t it not translated?

Kind regards

**Comment by lainsce** [comment]
Ah, I forgot to make them not translatable; they're internal names for some widgets.
You can leave them untranslated.

**Comment by Etamuk** [comment]
Thank you!
