### ISSUE TITLE
Keyboard shortcut for text formatting

### ISSUE THREAD

**Issue by gutsavgupta** [lainsce/notejot#224]
## Can we please add some keyboard shortcut for formatting

* example `ctrl+shift+L` for enabling a bullet
* example `ctrl+-` for strikethrough
* maybe `ctlr+u` for underline

This can ease down the workflow a lot. Let me know if this make sense
Thanks!

**Comment by lainsce** [comment]
:+1: I'll work on this soon.

**Comment by lainsce** [comment]
Moving this issue to #227, closing...
