### ISSUE TITLE
Use a different format for saving data

### ISSUE THREAD

**Issue by sonnyp** [lainsce/notejot#226]
Thanks for your apps, I enjoy them !

Notejot uses a single JSON file to saves notes. It's a pretty big design flaw IMHO. Any error in writing will results in invalid JSON and Notejot won't be able to read anything.

[Zim](https://zim-wiki.org) use plain files and does it pretty well with formats that are more robust to writing errors than JSON.
Other options include database such as SQLite or append-only format.

A bit anecdotal at this point but my notes disappeared (I had a backup) a while ago and while I couldn't pin point the issue; an error at writing resulting in invalid JSON seems most likely. Notejot flathub 2.7.4

**Comment by lainsce** [comment]
I would love if someone would help port the saving and reading all to a better format,
as I don't know how to work with databases or do fancy unique files in Vala.

But I'm sure that the current backend, which uses a library, did a lot of JSON error
checking to ensure it never writes bad JSON as it's used in other apps.

**Comment by 1Yanik3** [comment]
I would love if this would become a feature, preferably using Markdown files for each note

**Comment by sonnyp** [comment]
> But I'm sure that the current backend, which uses a library, did a lot of JSON error
checking to ensure it never writes bad JSON as it's used in other apps.

If you are referring to JSON-GLib, indeed, I have no doubt it outputs correct JSON.
The problem is not with serialization but rather any writing error that may occur due to hardware failure, unexpected process termination or simply a bug in Notejot.

> I would love if this would become a feature, preferably using Markdown files for each note

Notejot isn't a markdown application so I imagine this might be out of scope.

However, it raises the interesting question of the overlap between Notejot and the merge of quilter with apostrophe.

If Apostrophe gains Quilter sidebar then Notejot might become redundant for me.

**Comment by lainsce** [comment]
Notejot is a notes app which at the user's choice puts them in notebooks. It's meant to be simple and easy, no additional learning curve.

Completely different to using Quilter+Apostrophe, which requires knowledge of Markdown and has more complex tooling.

**Comment by lainsce** [comment]
Moving this issue to #227, closing..
