### ISSUE TITLE
HTML tags show up in sidebar

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#228]
While editing the first line of a note, HTML tags often show up in the note's title in the sidebar:

![image](https://user-images.githubusercontent.com/1908896/115532997-9a276800-a296-11eb-958f-06850fcb571f.png)

(This is current git master built in Builder)

**Comment by lainsce** [comment]
Once I port the note content widget to be a TextView using tags for formatting and saving/loading it properly, then this won't happen. :sweat_smile:

**Comment by lainsce** [comment]
Fixed~
