### ISSUE TITLE
Add padding to current notebook tag in bottom righthand corner

### ISSUE THREAD

**Issue by hanaral** [lainsce/notejot#233]
#### Issue

@lainsce Here you go!

The label showing the current notbook isn't as nicely spaced out as other widgets; there is significantly less space between the text and the right side of the window than the borderbox above it

![Screenshot from 2021-04-25 16-16-42](https://user-images.githubusercontent.com/58219504/115999013-f1ed0880-a5e1-11eb-9d48-ea69d301fd17.png)

**Comment by lainsce** [comment]
Fixed
