### ISSUE TITLE
Missed updating version number in meson.build

### ISSUE THREAD

**Issue by musicinmybrain** [lainsce/notejot#236]
In version 3.0.1 (and currently in git `master`) the project version is still `'3.0.0'` in `meson.build`.

**Comment by lainsce** [comment]
That's by design, I don't update it for x.x.1 to 9 releases. If it was 3.1.0, then I'd update it.

**Comment by davidak** [comment]
Such a design does not make sense. You want a user to state the version in bug reports, but you show a wrong version. This will harm you and confuse the users.

**Comment by lainsce** [comment]
The idea is that I prefer to think of x.x.0 releases as milestones inside a x.0.x release, they're minor updates at most. So stating the version as reported by the app is correct as it's the "series" the app is in currently.
