### ISSUE TITLE
Leaflet folds too early

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#237]
The leaflet currently folds at >800px, which is a bit wide for a single pane. I'd try folding at about 650-700px instead.

Side note: longer term it'd be cool if we could have the sidebar dynamically shrink a bit before it folds, that way the treshold could be even lower.

**Comment by lainsce** [comment]
To be fair I didn't change it from defaults still. :p

**Comment by lainsce** [comment]
Update, I can't yet do this.

https://gitlab.gnome.org/GNOME/libhandy/-/issues/390 

There's an open issue to fix this in libhandy/libadwaita so that I can set the fold width.

**Comment by lainsce** [comment]
Fixed locally, just have to push after I finish the small UI updates.

**Comment by lainsce** [comment]
Fixed.
