### ISSUE TITLE
Doesn't handle long lines

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#238]
Long lines break both the sidebar (as text is not truncated) and the content view (horizontal scrolling):

![image](https://user-images.githubusercontent.com/1908896/116234876-70ba8080-a75d-11eb-811e-11dea7954acb.png)

**Comment by lainsce** [comment]
Oh, I knew there was something I missed with the TextView. As for sidebar box, yeah, I'll look into this.

**Comment by lainsce** [comment]
Fixed
