### ISSUE TITLE
Delay when going back

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#239]
When clicking the back button there's a ~200ms delay before anything happens. It's brief, but long enough to notice :)

**Comment by lainsce** [comment]
How much should it be? 100ms is too fast.

**Comment by bertob** [comment]
After checking again, the delay is quite a bit longer than i estimated, I'd say north of 500ms. It also sometimes stops midway through or drops frames.

**Comment by lainsce** [comment]
This is weird.. I don't do anything special or hardcoded with the back button. It just moves back to the note list view, that's it.

**Comment by lainsce** [comment]
Should be fixed.
