### ISSUE TITLE
No close button when leaflet is folded

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#240]
Currently the close button is hidden when the leaflet is folded, so you can't easily close the app in that state.

On mobile close buttons are hidden system-wide via window decoration layout (IIRC), so there's no reason to explicitly hide them on the app side.

**Comment by bertob** [comment]
Correction: There's a close button, but only on the content pane, not when you're on the top-level view.

**Comment by lainsce** [comment]
Oh, I forgot to use the property in the folded lambda instead of the UI file when I was porting to GTK4; good catch! :)
