### ISSUE TITLE
When deleting a note which is not at the top of the list, the first note in the list is being deleted instead.

### ISSUE THREAD

**Issue by wendybug** [lainsce/notejot#242]
Hello,

* Describe the issue

When I have a collection of notes, for example one for each day of the week, with Monday the first note, if I delete the third one down (Wednesday), then Monday gets deleted instead.

* State what version you're using
I am using the latest Flatpak, which I installed a couple of days ago (2021 April 25). I am running it on Kubuntu 20.04.2 LTS.

********
As a side request... it would be really nice to be able to choose the order of the notes. 

Thanks,

wendy

**Comment by lainsce** [comment]
Could you update your Notejot version, and see if it happens again?

**Comment by wendybug** [comment]
Updated and fixed.

Thank-you.

**Comment by wendybug** [comment]
I spoke to soon...

I have several notes and populated them with text. Came back to them a few hours later and I am having the same issue.
I click on the ... tab where you can change the note colour or trash a note. If I trash a note down the list, it has gone back to trashing the one at the top of the list. 

I look forward to it working in the future and will give it another go in a few weeks, as the simplicity of it appeals to me.

w

**Comment by lainsce** [comment]
I think that I'll remove the popover on right click on the list, as it's not discoverable, and also is difficult to do on Mobile.
