### ISSUE TITLE
Option to make the application look like default Adwaita

### ISSUE THREAD

**Issue by jvnknvlgl** [lainsce/notejot#243]
I'm using the newest version of the application from Flathub (3.0.0), and I like what it does very much! I do wonder though: would it be possible to add the option to make it follow the standard adwaita theme? That way it fits in much better on my system, because right now it looks a bit out of place.

**Comment by lainsce** [comment]
Adwaita isn't a "thing" in GTK4, instead, one has the "Default" style. Also, it's not a "theme", but a style, difference being that you can just use a custom style instead of "Default".

I simply added things on top of it, so to do that, I'd need to remove all I added and break my app's style.
