### ISSUE TITLE
dark mode not in effect on start

### ISSUE THREAD

**Issue by admun** [lainsce/notejot#244]
I set dark mode in app, however, the app not render in dark mode on start

I am using 3.0.0, installed using flathub repo on Fedora 34

![image](https://user-images.githubusercontent.com/684815/116769172-0d478180-a9ef-11eb-9feb-200b7129afe3.png)

**Comment by admun** [comment]
I just found that after reboot, the problem went away. Not sure what cause the issue in the 1st place

**Comment by lainsce** [comment]
Maybe it was just some small flatpak hiccup.. sometimes it happens.

Since it's fixed, closing.

**Comment by dtbj** [comment]
@lainsce in my fedora 35 I am using the same app but I don't even have the option to enable dark mode why??

**Comment by lainsce** [comment]
Notejot is prepared for the changes in GNOME 42 regarding Dark Mode.

**Comment by cobalt2727** [comment]
How can we manually enable dark mode? I don't see any button for it and my distro does not have Gnome 42 (running Pop!_OS 21.10).

**Comment by lainsce** [comment]
There is a small tool made by exalm that they use for testing the mode change, you could compile that and use it. Pop!_OS won't upgrade to GNOME 42 because of off-topic drama.
