### ISSUE TITLE
note corrupted on load

### ISSUE THREAD

**Issue by admun** [lainsce/notejot#245]
after created a note, it seems corrupted and stuck in "loading...." on app restart

fedora 34, running 3.0.0 installed from flathub repo

![image](https://user-images.githubusercontent.com/684815/116769988-1b989c00-a9f5-11eb-8fba-ef9aa636ddf9.png)

The saved_notes.json looks like (.var/app/io.github.lainsce.Notejot/data/io.github.lainsce.Notejot/saved_notes.json):
```
[["","Friday, 30/04 20∶33","","#e66100",""],["","Friday, 30/04 20∶37","|New Note 1|\n\nThis is a text example.","#fff",""]]
```

**Comment by lainsce** [comment]
This is already fixed on this repository, but I need to make a new release to have it available on FlatHub.
But, as you can see from the other two bugs, I haven't fixed all there is to fix, so I can't ship a buggy release.
