### ISSUE TITLE
" com.github.lainsce.notejot " is this your project ?

### ISSUE THREAD

**Issue by aiamuzz** [lainsce/notejot#246]
Hi,

" com.github.lainsce.notejot " is this your project ?

![image](https://user-images.githubusercontent.com/3283676/118016175-b63c9780-b372-11eb-9801-7f49726beec6.png)

As you can see the note slip has a black frame all round ... I would really appreciated if you help me remove it !!!

PS : I had installed this " com.github.lainsce.notejot " from flathub ... but i see the name is currently changed to " **io**.github.lainsce.**N**otejot " i

thanks.

**Comment by aiamuzz** [comment]
> but i see the name is currently changed to " **io**.github.lainsce.**N**otejot " i

This UI is totally different to the one i had installed a while back ...

**Comment by aiamuzz** [comment]
I just figured version 1.6.3 had this UI ... It was such a great UI ... Why did you end up changing it ?

**Comment by lainsce** [comment]
> I just figured version 1.6.3 had this UI ... It was such a great UI ... Why did you end up changing it ?

Because the focus of the app changed, and because it was a nightmare to code saving all the notes without data loss. :)

**Comment by lainsce** [comment]
I wonder why the old app version is still available if I made it deprecated in FlatHub

**Comment by aiamuzz** [comment]
> I wonder why the old app version is still available if I made it deprecated in FlatHub

Its not available currently ... I had installed it long back and i was doing some cleaning up and i came across it ... 

This is the only 'Post It' styled notes and i loved only this one ... and unfortunately its been deprecated !!! ... :disappointed:

**Comment by aiamuzz** [comment]
> > I just figured version 1.6.3 had this UI ... It was such a great UI ... Why did you end up changing it ?
> 
> Because the focus of the app changed, and because it was a nightmare to code saving all the notes without data loss. :)

Is there any way you can help me remove this black frame all round the post-it ?
Could it be bcos i am using it as a flatpak ?
Does a non-flatpak installation run without this black frame ?

FYI ... I am using **DeepinLInux** which has windows effect enabled ... just in case could that be causing it ?

**Comment by lainsce** [comment]
Well, I'm not going to fix an old version in an unsupported environment such as Deepin, so sadly you're on your own.
It's not due to flatpak.

Old versions were made for elementary OS, the new versions being made for GNOME.

**Comment by aiamuzz** [comment]
> Well, I'm not going to fix an old version in an unsupported environment such as Deepin, so sadly you're on your own.
> It's not due to flatpak.
> 
> Old versions were made for elementary OS, the new versions being made for GNOME.

no problem ... found the feature rich **Globonote** to my satisfaction ...
thanks for looking ...

**Comment by lainsce** [comment]
That's the beauty of Linux, there's lots of alternatives :D
