### ISSUE TITLE
[Feature Request] Export Notes as Markdown/Other

### ISSUE THREAD

**Issue by theotheroracle** [lainsce/notejot#248]
would it be possible have the app save the notes as markdown to an external directory ?

can work on an implementation if the idea is alright

**Comment by lainsce** [comment]
Go ahead!

Use the triple-dot menu when a Note is opened to store the "Export Note…" menu item, then code what's necessary to export the note. :)

**Comment by theotheroracle** [comment]
ok, one more question, could i add an option to save as markdown automatically ? it could use markdown instead of json, or just export to markdown on app close, but that seems a bit more convoluted

**Comment by theotheroracle** [comment]
( for context, there's an app called noteless on android, and notable on desktop, that save markdown files to an external directory that can be synced, but i much prefer the UI of this one, and would like to be able to use it if possible but i dunno if that's out of the scope of this project )

**Comment by lainsce** [comment]
As long as moving to Markdown makes saving the note's metadata like colour and notebook possible.. That's why it's in JSON right now.

**Comment by theotheroracle** [comment]
i think metadata like that could be stored in comments, as suggested in [this post](https://stackoverflow.com/a/32190021)
comments like 
```
[colour]: # red
```
should be fine for storing metadata

does that work for you ?

**Comment by lainsce** [comment]
Alright!

So, feel free to start coding :)

**Comment by theotheroracle** [comment]
awesome, thanks ^~^

**Comment by lainsce** [comment]
@theotheroracle Any updates? :)

**Comment by theotheroracle** [comment]
heya ! i'm sorry, i haven't gotten too much done, i've been busy with my job, and my dev PC is currently borked, but i'll try to work on it as soon as i can

**Comment by lainsce** [comment]
No rushes, just wanted to know what's up haha

**Comment by environmentalcode** [comment]
Hey @theotheroracle, do you have any updates? This app looks sleek but it's kinda useless given that notes can't be synced betweed devices as it uses JSON and not markdown, plain text or other file formats.

**Comment by theotheroracle** [comment]
> Hey @theotheroracle, do you have any updates? This app looks sleek but it's kinda useless given that notes can't be synced betweed devices as it uses JSON and not markdown, plain text or other file formats.

i got a new laptop and i have a bit more free time on my hands, so i'll take another crack at this, thanks for reminding me <3

**Comment by lainsce** [comment]
Due to an incoming backend super re-write, perhaps what I'm planning to do may add value to this issue.

I'm planning to rewrite the backend so that the core is the JSON, but using the Repository pattern, instead of the DIY mess that is now here.

Perhaps, this might make the job easier to have an export button in the menu.

**Comment by theotheroracle** [comment]
what do you mean by repository pattern ?

**Comment by lainsce** [comment]
Read up on it here:

https://blog.kylegalbraith.com/2018/03/06/getting-familiar-with-the-awesome-repository-pattern/

**Comment by theotheroracle** [comment]
should i wait for you to update the repo pattern before doing anything then ?

**Comment by lainsce** [comment]
It's already all done. You can start your things :)

**Comment by lainsce** [comment]
Here's a mockup of where the Export button would be:

![Frame 1](https://user-images.githubusercontent.com/4886639/145645287-392e3d14-3e19-48e8-983b-2ba01b284bca.png)

**Comment by theotheroracle** [comment]
looks good to mr

**Comment by user82622** [comment]
Would usefull to make the most common markdown formatting options (titles, boxes, code quotes) available as formatting options (with buttons (like the listing item option) and correctly display/transform them it in the writer. That would make this tool super powerful cause it would be possible to do markdown formatting over the ui.

**Comment by theotheroracle** [comment]
yeah definitely, i could look into that if that's ok with @lainsce

**Comment by lainsce** [comment]
If you can rework the formatting to work with Markdown glyphs instead of what it has now, and at least add what would make sense in a simple notes app for the missing format options, then I give the ok. I just don't want all the formatting options and the kitchen sink as that would defeat the simple part of Notejot.

**Comment by macdabby** [comment]
This is a little off topic but related. I have been looking for a notes app that would sync with imap. Apple uses this for both Mac and iOS and I think there are some webmail clients that use the same. I think this is a little better than exporting to a folder to sync, because the sync is done automatically in the same app. But in this scenario it uses an html format that can also have embedded image data (base64 encoded right into the <img> tag.) I haven't found any Linux or android app that's compatible with that. What do you think about this? Would it be a better solution?

**Comment by theotheroracle** [comment]
i think it would be fairly trivial to integrate with goa

**Comment by lainsce** [comment]
OK, so let's make it a multipart PR I guess, @theotheroracle? XD

First PR being the whole exporting of notes, and second PR being integration with GOA "notebooks" in a separate sidebar list where only Synced Notebooks are, with a refresh button by the header.

**Comment by theotheroracle** [comment]
yeah that sounds good

**Comment by lainsce** [comment]
The thing is, we'd have to wait for GOA to be ported to GTK4, since it only has a GTK3 version.

**Comment by luixal** [comment]
Hi!

Just found this app today and it's really nice, thanks!

About this issue, frist thing I thought when writting my first note was: _"why is this not using markdown?!?"_

I think it would be a perfect match. I mean, not exporting to markdown, but using markdown in the app's editor itself.

**Comment by theotheroracle** [comment]
maybe there could be a markdown mode ? wouldn't be too hard to implement once exporting was finished .

**Comment by dag7dev** [comment]
yes, I strongly agree with @theotheroracle , it would be wonderful to have the default note in markdown (or live previewing markdown, like Obsidian).

I've just discovered this app, I fell in love with it: keep it up!

**Comment by lainsce** [comment]
**UPDATE**

I have updated the formatting syntax to closely resemble Markdown where possible.  
The outlier is Underline which uses \_the alternate syntax for italic\_.

This oughta make the exporting much less problematic.

**Comment by lainsce** [comment]
**UPDATE**

I have fixed this issue myself; notes will be able to be exported in a fixed format but favouring Markdown.

**Comment by theotheroracle** [comment]
sorry i wasn't able to do this and i'm glad you were able to
