### ISSUE TITLE
[Feature Request] Support for Labels

### ISSUE THREAD

**Issue by 116davinder** [lainsce/notejot#249]
Hi Everyone,

is it possible to add support for labels in this application so we can label to notes and search them later with labels?

**Comment by lainsce** [comment]
What you want to do is use Notebooks. Move a Note to a Notebook with the three-dot menu when a Note is open, and it should be easy to select only that Notebook with the header bar centered dropdown menu on the sidebar. That same menu has the Create Notebooks dialog. That should help you do what you wanted.

Also, everyone = me lol.

**Comment by 116davinder** [comment]
Hi @lainsce 
Thanks a lot for the really nice app.

The current Search method is limited to the header of notes and doesn't care what is being written inside, I know that parsing each and every note and providing better results is too much for this app. 

To not make it more complicated, I was thinking, if we add extra tags/labels on each note then search for header + extra tags/labels which won't impact performance and code complexity.

what are your thoughts on it?

**Comment by lainsce** [comment]
If you want to add the functionality and improve search, I welcome you to make a Pull Request with this and we'll take from there. I would be grateful if you did it because you know exactly what you want to add, and it'd be faster to implement if we discuss it as you implement it.

**Comment by 116davinder** [comment]
@lainsce, Initial my idea was to implement it but then I saw the app is being written in **Vala** which I never heard of ( bad for me ), I will try to find free time to learn and implement this feature.

Thanks a lot for your reply.

**Comment by lainsce** [comment]
Take your time, there's no rush :)

**Comment by lainsce** [comment]
Sorry, but I've decided to close this because I think Notebooks will help label notes faster than in-text labels.
