### ISSUE TITLE
[Feature Request] Quick notes

### ISSUE THREAD

**Issue by kdwk** [lainsce/notejot#251]
## Suggestion
It would be great if we can add a 'quick notes' functionality like that of iPadOS and macOS. It would allow users to create quick notes with a keyboard shortcut, which when pressed will create a quick notes window in the bottom right corner of the screen, with only the note-editing part of the app (but not sidebar of the 'main window', like when clicking the app icon to open the app). I suggest that a new note is created every time this is invoked, and the window closes itself when it loses focus so the user wouldn't have the extra burden of dismissing it.

## Prior Art
![Screenshot from 2021-07-08 09-47-29](https://user-images.githubusercontent.com/39268094/124849556-9243ae00-dfd1-11eb-81e9-6d9526326dad.png)

**Comment by lainsce** [comment]
It is in the plans, to be able to open just a note window independent from the main UI, in a way that the Main UI is a window by itself, and the note is popped out into an independent window. I just need to plan how this will work, better.

**Comment by lainsce** [comment]
Thin king about this, I feel like the feature will add unnecessary complexity
