### ISSUE TITLE
[Feature Request] Create a note inside a selected notebook

### ISSUE THREAD

**Issue by eladyn** [lainsce/notejot#252]
First of all, I somehow really love this little application! Thanks!

I would like to propose that newly created notes are assigned to the selected notebook.

The reason, I think that this would be a somehow logical behaviour, is the following:

1. select an existing notebook
2. click the "create note"-button or Ctrl+N

The created note is not assigned to any notebook and does not appear in the list. That means that while the new note appears on the right pane, you can't see, where your note actually has been put. 

I might even look into this myself, but I have never ever read any Vala before, so don't expect anything from me in the near future... :grin:

**Comment by lainsce** [comment]
Fixed
