### ISSUE TITLE
High CPU usage when app left open for a while

### ISSUE THREAD

**Issue by Frivolous2** [lainsce/notejot#254]
## Hello! If you found an error in this app, follow this template:

When app is left open for an hour or so, CPU usage becomes abnormal.

* State what version you're using
Flathub 3.0.0 on Fedora Workstation 34

* Take a screenshot of the problem, then use the Markdown property for it:  ![Screenrec](https://user-images.githubusercontent.com/57101103/127206959-b3841650-58fc-4954-a0f1-69f9009288ec.mp4)

Thanks!

**Comment by lainsce** [comment]
This might be because I haven't updated Notejot's GTK4 to a newer version since I started my developer break/vacation.. This will be fixed very quickly on August.

If it's not GTK4, then I'll look for stuff that's CPU costly and rewrite it.

**Comment by lainsce** [comment]
Yes, my suspicions were correct, it should be fixed now.
