### ISSUE TITLE
Contrast needed on paper theme

### ISSUE THREAD

**Issue by jacksongoode** [lainsce/notejot#256]
![image](https://user-images.githubusercontent.com/54308792/129285748-0b9c07d6-593f-477a-998f-d9462358eb81.png)

This is either a bug or because of the inherited themes (on Fedora 34, with RPM installation). The text for the menu items should be darker or have some contrast.

**Comment by lainsce** [comment]
This isn't the repository for Quilter.

**Comment by jacksongoode** [comment]
Lmao, it's been a long day!

**Comment by lainsce** [comment]
And before you open an issue, you must disable Dark Theme on Tweaks before using Quilter, because it's a thing that's against the defaults expected by Quilter. :P
