### ISSUE TITLE
[Bug] App won't use dark mode when there are no notes

### ISSUE THREAD

**Issue by DiegoIvanME** [lainsce/notejot#258]
## App will always start on light mode

Notejot will use light mode when no notes have been created. I'm not sure if this is a bug or intended design feature

Instructions to recreate:
* Create a new note
* Enable dark mode
* Send the note to trash
* Close the app
* The app will start on light mode

* Versions: 3.1.0 (Development and Flathub stable)
* [Evidence](https://youtu.be/2ueb10t_siI)

Final note:
If this was a bug can I try to fix it? I'm relatively new to GTK development and would like to contribute to open source. Thanks in advance!

**Comment by lainsce** [comment]
If you're motivated to fix it, then go ahead! :)
