### ISSUE TITLE
Notejot not available in Elementary AppCenter by default

### ISSUE THREAD

**Issue by JohnDumpling** [lainsce/notejot#269]
After the release of eOS 6, Notejot is not included in the AppCenter. After adding the Flathub repository by sideloading a random Flatpak app, Notejot appears as a non-curated app with a Gnome icon and UI look (does not fit the Elementary stylesheet).

**Comment by lainsce** [comment]
That's what it is, Notejot isn't an elementary app anymore, it follows GNOME guidelines.
