### ISSUE TITLE
Metadata release date and Flathub repo manifest

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/notejot#271]
Hi, I noticed that release dates in the metadata file are a year behind (could be causing what's mentioned in [this comment](https://github.com/lainsce/notejot/pull/266#issuecomment-901803985)).

I also forgot to mention that the Flathub repo manifest should be changed for the latest changes in my last MR to take effect.

**Comment by lainsce** [comment]
I'll look into this

**Comment by lainsce** [comment]
Fixed. :sweat_smile:
