### ISSUE TITLE
wrong version in about

### ISSUE THREAD

**Issue by davidak** [lainsce/notejot#282]
the about dialog displays version 3.1.0, but it's actually 3.1.2

![Screenshot from 2021-09-04 20-03-36](https://user-images.githubusercontent.com/91113/132104177-e8b37c4b-14f6-42cf-8726-6448fd483834.png)

it seem to need an update in https://github.com/lainsce/notejot/blob/ca00b63aa5e838bcc7d0abbdc07a0f52d3594c0b/meson.build#L1

this was noticed in https://github.com/NixOS/nixpkgs/pull/136702

**Comment by oscfdezdz** [comment]
Check [this comment](https://github.com/lainsce/notejot/issues/236#issuecomment-826850246) .

**Comment by lainsce** [comment]
See the above :)
