### ISSUE TITLE
Window display all white

### ISSUE THREAD

**Issue by luta78** [lainsce/notejot#283]
hello, im in archlinux and gnome, and i install Notejot with aur, and cant make it working, all time its display a white window.

if i run it from the terminal i get 

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.624: Error building template class 'NotejotMainWindow' for an instance of type 'NotejotMainWindow': .:0:0 Duplicate object ID 'placeholder' (previously on line 0)

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_menu_button_set_popover: assertion 'GTK_IS_MENU_BUTTON (menu_button)' failed

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_widget_get_style_context: assertion 'GTK_IS_WIDGET (widget)' failed

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_style_context_add_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(io.github.lainsce.Notejot:23171): GLib-GObject-WARNING **: 22:39:26.664: invalid (NULL) pointer instance

(io.github.lainsce.Notejot:23171): GLib-GObject-CRITICAL **: 22:39:26.664: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_menu_button_set_menu_model: assertion 'GTK_IS_MENU_BUTTON (menu_button)' failed

(io.github.lainsce.Notejot:23171): Gtk-CRITICAL **: 22:39:26.664: gtk_list_box_set_filter_func: assertion 'GTK_IS_LIST_BOX (box)' failed

Thanks!

**Comment by lainsce** [comment]
Notejot is meant to be installed via Flatpak. Native packaging methods are discouraged as **they will fail**.
