### ISSUE TITLE
Back swipe gesture goes to empty screen

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#286]
When swiping back from a note you end up on an empty gray screen rather than the top-level view.

git master, built in Builder

**Comment by lainsce** [comment]
I haven't been testing much the mobile/touch functionality as I don't have a Linux mobile or a touchpad device. :(

**Comment by bertob** [comment]
I was only testing it on a regular laptop touchpad but yes, I assume this affects touchscreens as well.

**Comment by lainsce** [comment]
Fixed, found the problem :3
