### ISSUE TITLE
Custom title isn't bold

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#287]
The note title is bold initially, but when I edit it my new real title is no longer bold:

![image](https://user-images.githubusercontent.com/1908896/132669517-17423cfb-29cc-46c1-81e6-ba654aac615a.png)

**Comment by lainsce** [comment]
The bold styling is just a placeholder formatting suggestion, any title can be any formatting. :)

**Comment by bertob** [comment]
Maybe, but from a user perspective it feels counterintuitive. I'd have assumed the title to always be bold.

**Comment by lainsce** [comment]
The title is always the first line, so it should be intuitive seeing the title change in the sidebar as the user provides the first line independent of formatting :)
