### ISSUE TITLE
Dark border on color dots

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#288]
The color dots have a very dark border which looks out of place. I'd use a semi-transparent overlay on the orange, or some darker orange tone.

![image](https://user-images.githubusercontent.com/1908896/132669692-6982c787-01b6-4e23-915f-fbd56e4a31db.png)

**Comment by lainsce** [comment]
I think I know what is doing this, will fix soon™

**Comment by lainsce** [comment]
Fixed :3
