### ISSUE TITLE
[Design] Sort sidebar items by most recent edit

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#290]
The notes in the sidebar are currecntly sorted by creation date, which makes it hard to find stuff if you have more than a handful of notes. I'd sort them by edit date, from recent to less recent.

**Comment by lainsce** [comment]
Hmm... I'd have to constantly change the timestamp of notes as soon as a change is made then resort.

**Comment by bertob** [comment]
You sure? I built master and it's still not changing the sorting when editing notes.

**Comment by lainsce** [comment]
Now it's solved for real. XD
