### ISSUE TITLE
[Design] Preserve width of notes list

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/notejot#291]
Text in the notebook switcher takes the full width of the view it needs, which IMO should be limited to avoid extreme cases. It also applies to `All Notes` and `Trash` labels when they are translated to some language that takes much more width than the original text.

There are properties for GtkLabel like `ellipsize` and `max_width_chars` that are probably handy for this.

Notejot 3.1.3

![notejot](https://user-images.githubusercontent.com/42654671/133589564-b0e3887f-802d-4d86-896c-0cac53f983aa.gif)

**Comment by lainsce** [comment]
The problem here is that it's a GtkMenuButton which doesn't have either of those props. Maybe it's time to rethink this part of the UI.

**Comment by lainsce** [comment]
![shot](https://user-images.githubusercontent.com/4886639/134924725-3d4499c3-1101-4462-bf96-cc1f61da5ec3.png)

Fixed by making the notebook selector a sidebar with the All Notes and Trash items up top.
