### ISSUE TITLE
Strikethrough does not work completely

### ISSUE THREAD

**Issue by Frivolous2** [lainsce/notejot#292]
I'm trying to use strikethrough in a note but it seems to ignore the first row in it:
![Screenshot from 2021-09-23 22-20-31](https://user-images.githubusercontent.com/57101103/134732368-ab27996c-a9a7-4212-8ad2-c0617cf34e42.png)
It's on version 3.1.3 from Flathub.

Thanks!

**Comment by lainsce** [comment]
Is there any new lines in-between the ~? :)

**Comment by Frivolous2** [comment]
I don't think so?
And what gets stricken through depends on window size?

https://user-images.githubusercontent.com/57101103/134752373-ed7d4a15-157b-4b95-8962-16a010ab79f6.mp4

**Comment by lainsce** [comment]
The code looks through the text and determines what should be the start of lines until their ends based on font character dimension data, and maybe it's thinking that a line that's not wide enough shouldn't be strikenthrough. If it's buggy, then it's GTK not Notejot that's the problem, as it's not detecting it properly.

**Comment by Frivolous2** [comment]
Yeah, I checked again for endlines and I don't think there's any. I'm not sure how to report this to GTK though.

**Comment by lainsce** [comment]
You could report this strange behavior at [here in their repository for GTK](https://gitlab.gnome.org/GNOME/gtk); but please report that the stringbuilder text functions used inside Notejot are what's causing this: [Beginning from this line](https://github.com/lainsce/notejot/blob/master/src/MainWindow.vala#L524) to the relevant functions in Textfield.vala.

Maybe they'll relocate the issue to a different repository, so keep your eyes peeled for changes. Closing this issue, however.

**Comment by Frivolous2** [comment]
I’m a total noob at this, I think it might be better if you reported it. 😅

**Comment by lainsce** [comment]
Wait a second, I think it's not GTK's fault. There's something missing in the code to handle strikethrough maybe, since all other types of formatting are working.

**Comment by lainsce** [comment]
This seems to have fixed itself when I updated the SDK and ran NotejotDevel, so it should be fixed on release.
