### ISSUE TITLE
Default title never gets changed in saved_notes.json

### ISSUE THREAD

**Issue by gwutz** [lainsce/notejot#296]
* Describe the issue

I looked into the saved file in order to understand the reasoning behind marking bold text with | and realized that the title of the note in that file never gets changed. So i always have one field "New Note 1" for every note in there.

* State what version you're using

3.1.0

**Comment by lainsce** [comment]
This is fixed in 3.2.0, I just have to fix one last thing before publishing that.

**Comment by gwutz** [comment]
Awesome - i just saw that and was not sure if this is ever used and therefore i wanted to report it.
