### ISSUE TITLE
flatpak problem during install

### ISSUE THREAD

**Issue by methane4** [lainsce/notejot#297]
During install this happens:
![Screenshot from 2021-09-29 17-50-21](https://user-images.githubusercontent.com/46012160/135331695-74519d56-aade-489f-a1ab-7ec58d4bed95.png)

i have also made an issue here: https://github.com/flathub/io.github.lainsce.Notejot/issues/1

**Comment by lainsce** [comment]
This isn't in Notejot's hands. Closing.
