### ISSUE TITLE
Panel overlap glitch at narrow widths

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#298]
Somehow it's possible for the panels to overlap when resizing to a smaller widths:

![image](https://user-images.githubusercontent.com/1908896/135347875-bd94b8e3-bb16-4a4f-b14e-686a88b41c82.png)
![image](https://user-images.githubusercontent.com/1908896/135348019-0c995be5-69b8-4232-9ec6-411dafff7a93.png)

**Comment by lainsce** [comment]
Can confirm this is fixed in the next release
