### ISSUE TITLE
Left-align menu items

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#306]
These should be left-aligned:

![image](https://user-images.githubusercontent.com/1908896/137293860-14eb6cdf-d676-4914-ab40-dd3c1e1f21ab.png)

**Comment by lainsce** [comment]
I am 100% sure until proven otherwise. I did ask before in Matrix if I could replicate ModelButton behaviour but afaik GTK devs said due to the custom widget it was a no.

**Comment by lainsce** [comment]
OK, after seeing how Text Editor does it, I could make this a reality on `master`
