### ISSUE TITLE
Crash during startup (attempt) / Permission problems

### ISSUE THREAD

**Issue by methane4** [lainsce/notejot#308]
After installing, when i start notejot i get a crash error. 
![Screenshot from 2021-10-16 15-17-25](https://user-images.githubusercontent.com/46012160/137590957-1a0f93f5-d66b-4bac-918f-286ab3da7c31.png)

Running it with `flatpak run` i get some info about it
![Screenshot from 2021-10-16 15-19-25](https://user-images.githubusercontent.com/46012160/137591009-ac982046-7eac-4e28-9b64-c107c04e7761.png)

With `Flatseal` i enabled `GPU accelaration(device=dri)`
![Screenshot from 2021-10-16 15-20-24](https://user-images.githubusercontent.com/46012160/137591090-19363a75-06fa-4ef2-becd-865fe7f309e3.png)

After that the app starts as normal. I suggest you check your flatpak permissions

**Comment by methane4** [comment]
I've created a PR that fixes this problem. 
https://github.com/flathub/io.github.lainsce.Notejot/pull/2

**Comment by lainsce** [comment]
Sounds like a problem in your installation. One shouldn't need to expose GPU to a flatpak.

**Comment by thomasaull** [comment]
I'm getting the same error, it's a new installation of elementary OS 6, so there shouldn't be be anything I've screwed up. Any chance you can look into it? It's a great application and I've used it all the time with elementary os 5

**Comment by methane4** [comment]
@thomasaull Did you confirm its the same issue? Try my fix.

**Comment by lainsce** [comment]
I wonder if this is an issue with hardware like NVidia? It's completely off my hands.

**Comment by lainsce** [comment]
In any case it's not a bug in Notejot.
