### ISSUE TITLE
When dark mode is enabled, the menu text is black when it should be white

### ISSUE THREAD

**Issue by freshgum-bubbles** [lainsce/notejot#309]
When I enable the Dark Mode option in NoteJot and open the hambuger menu, the items are in a black font. This means they are very hard to read when contrasted with the dark background.

## System Information

Dark theme: Adwaita Dark
Operating System: Fedora 35 (`5.14.10-300.fc35.x86_64`)
NoteJot version: 3.1.0, distributed via Fedora's RPM repository

I am not sure if this is also an issue in the Flatpak version (3.2.0) as I can not find an option to enable dark mode with that version of the application; that version also does not respect the system's theme settings, using light when I have selected "Adwiata Dark" in GNOME Tweaks.

freshgum

**Comment by freshgum-bubbles** [comment]
So... here's the funny part: I can't actually *get* a screenshot of this. Whenever the hamburger menu is open, `xwd` dies with `Can't grab the mouse` and... the moust can't do anything *except* interact with the hamburger menu. Keyboard is totally locked too. I have never seen anything this strange before.

**Comment by lainsce** [comment]
Notejot starting with 3.2.0 is equipped to change to dark mode only with the system-wide change that's coming in GNOME 42 and is now in elementary OS. Using Tweaks to change stuff makes the issue invalid as you're on your own.
