### ISSUE TITLE
[Bug] Note tiltes are note saved

### ISSUE THREAD

**Issue by carallo** [lainsce/notejot#310]
Hi! First of all thank you for this great app!

After last update I've noticed you've added a "Title" entry in the app, which I find great. Nevertheless I've noticed that changing the Title does not save it to the saved_notes.json file, so when restarting the app the title gets reverted back to "Saved Note...". Manually editing the .json file does correctly reflect in the app.

**Comment by lainsce** [comment]
Due to a GTK4 limitation, just changing it won't save it, you have to press Enter or the pencil icon by the side.

**Comment by carallo** [comment]
> Due to a GTK4 limitation, just changing it won't save it, you have to press Enter or the pencil icon by the side.

Was about to reply just that, I just noticed that clicking the pencil icon worked for saving it. I have to say it's a bit counter-intuitive as a behaviour, but if it's GTK4's fault there's not much to do. But just clicking enter is pretty easy, so not a big deal.

Thank you!
