### ISSUE TITLE
Translations improvements

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/notejot#313]
- [x] Merge po and po/extra. (https://github.com/lainsce/notejot/pull/314)
- [x] Broken translations on master. (https://github.com/lainsce/notejot/pull/315)
- [x] ~Untranslatable days of the week in subtitles.~

_Check comment history for original message._

**Comment by lainsce** [comment]
Feel free to make changes with PRs :+1:

**Comment by oscfdezdz** [comment]
I guess the last one requires manually adding the days of the week in text and making those lines translatable in Services/Utils.vala.

I don't have enough knowledge to do that yet, if you want to take over on that, that's fine with me or if you prefer to leave the issue open for a few more days until I have time to look into it :)

**Comment by lainsce** [comment]
I'll leave the issue open for as long as you need it open. :smile:

**Comment by oscfdezdz** [comment]
It seems like the last one was a false alarm. Installed with meson and translates fine, hope it's not a Flatpak issue 🤞🏼
I'll wait till next release to check it out.
![notejot](https://user-images.githubusercontent.com/42654671/141119267-a033cce4-e7c7-4d2a-87fc-fe00327ebd82.png)
