### ISSUE TITLE
Updating to 1.2.8 ate my previous notes!

### ISSUE THREAD

**Issue by Heiko-M** [lainsce/notejot#32]
Hi,
I've just updated to version 1.2.8, and now my previous notes are gone! Has the file been overwritten? If I was able to find my notes in my backup files, would they be compatible to the new version?

Otherwise, great app!

**Comment by lainsce** [comment]
They are compatible! 
I guess that by updating the internals on handling files, you've met with transitional notes. :smile: 
But don't worry, in 1.2.8, they're always saved unless you hit the trash button. Happy note jotting!

**Comment by Heiko-M** [comment]
Ok thanks. Just realized, I excluded .cache from my backups :/

**Comment by lainsce** [comment]
Well, if anything, now it's safer to write notes, since they only really delete if you hit the trash button.
