### ISSUE TITLE
Formatting issue when closing and opening

### ISSUE THREAD

**Issue by awelts** [lainsce/notejot#33]
I am using version 1.2.8 of this application and whenever I write notes and use the return key to give it a new line and some space in between sections of different ideas, close the app and reopen it, the text gets thrown to the first line. All line spacing i have put in has been removed and consolidated all the text to one line. I do not know if this is only me or is anyone else has experienced this and if there is something I can do to fix it.

**Comment by lainsce** [comment]
This is an issue I'm currently fixing for the next release, what a coincidence that you've opened a issue about this. :joy:

**Comment by awelts** [comment]
Okay awesome I didn't know if I was going crazy or not. I updated it
earlier today and love using it and when I had reopened it the formatting
went all nuts and was thinking was there some way that I saved it or
something before. Glad I'm not losing it! But your app is great and thanks
for the feedback as well!

**Comment by lainsce** [comment]
Fixed in 1.3.0, closing~
