### ISSUE TITLE
Cached libadwaita version breaks latest release

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/notejot#333]
I just updated to the latest stable release.
```
$ flatpak info io.github.lainsce.Notejot

Notejot - Anote sus ideas

          ID: io.github.lainsce.Notejot
  Referencia: app/io.github.lainsce.Notejot/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Versión: 3.4.6
    Licencia: GPL-3.0+
      Origen: flathub
   Colección: org.flathub.Stable
 Instalación: system
   Instalada: 5,5 MB
     Runtime: org.gnome.Platform/x86_64/41
         Sdk: org.gnome.Sdk/x86_64/41

      Commit: a8134fb4bb3ddcc3a48eff45c3850c523313dbdfcfed3aa606e91d53dc9a49fb
       Padre: c604058b81481a605ecac25ca9460323a47df42393411419cf356a8831610716
      Asunto: 3.4.6 (ac352b77)
       Fecha: 2021-11-28 09:01:13 +0000
```
This error happened to me locally with 53a68a546efc5bd03add1a95ee245fb67e883457 commit and I had to manually remove GNOME Builder's cache folder, so I guess a similar process has to be done.
```
$ flatpak run io.github.lainsce.Notejot

(io.github.lainsce.Notejot:2): Gtk-CRITICAL **: 13:11:30.786: Error building template class 'NotejotMainWindow' for an instance of type 'NotejotMainWindow': .:0:0 Invalid property: AdwLeaflet.can-navigate-back

(io.github.lainsce.Notejot:2): Gtk-CRITICAL **: 13:11:30.787: gtk_menu_button_set_menu_model: assertion 'GTK_IS_MENU_BUTTON (menu_button)' failed
```

![imagen](https://user-images.githubusercontent.com/42654671/143767211-9cc8ecc2-5c4d-40b4-a1b4-fac0a205871f.png)

**Comment by lainsce** [comment]
Yeah, it was a long long story this night with fixing Notejot. I have pushed an update to the flatpak manifest with this fixed, should be up in some minutes.

**Comment by lainsce** [comment]
Also if your Notejot app opened with a blank screen today, it's easy to fix things:

- Update Notejot again in flatpak
- Go to /home/lains/.var/app/io.github.lainsce.Notejot/config/glib-2.0/settings and change in keyfile the schema_version from 1 to 0.

That way your notes are safely migrated over.
