### ISSUE TITLE
[Feature Request] Filter Notes by clicking Notebooks in the sidebar

### ISSUE THREAD

**Issue by carallo** [lainsce/notejot#335]
Hi @lainsce,
Really love the new layout, Notejot keeps getting better and better!

I wanted to let you know about a bug I've noticed with the new 3.4.9 version. The notebooks area (under the trash bin) is not clickable for me. Instead, if I double click on a notebook the window gets maximised, and right click gives me the window menu, as if I was clicking on the window decoration bar.
I don't know if it's because I'm not using Flatpak version, but instead I've built from source. I'm on Manjaro with Gnome Shell.

Anyway, thanks for the great work, I love Notejot!

**Comment by lainsce** [comment]
It is a list of notebooks as labels, I haven't given them a clickable action.

Do you feel that they should be able to be clicked?

**Comment by carallo** [comment]
>Do you feel that they should be able to be clicked?

Well, I'm not an avid user of notebooks so for me it could also stay so, is not a big deal.
Nevertheless I think that intuitively when clicking them they should show on the notes list just the notes belonging to the notebook. At least that's what I was expecting when I saw the notebooks in the list, instinctively.

**Comment by carallo** [comment]
> I'll see if I can filter the notes list by making the notebooks list have selectable notebooks

Amazing! But if it's too much hassle, it's not such a big issue anyway ;)

Thank you!

**Comment by lainsce** [comment]
I have tested a lot of ways I thought would work, but a list only has one source of filtering at a time; so I decided to let it be, with filtering by note title with the searchbar.

**Comment by carallo** [comment]
Hi @lainsce, no worries. It's not so important, I just thought it would be more "natural", or intuitive, to click on a notebook and show only the notes in it. But it's not such a big deal, at least for me.
Thank you anyway for looking into it!

(Should I close this issue or leave it open for future purposes?)

**Comment by lainsce** [comment]
If a new way  that enables me to filter the notes arises, the issue will be reopen :)
