### ISSUE TITLE
[Question] Cannot find pinned notes on new design

### ISSUE THREAD

**Issue by carallo** [lainsce/notejot#336]
Sorry again, this is just a question this time.

I've got some pinned notes and I can see they are still pinned in the new design since they have the small pin icon to identify them. Nevertheless I cannot seem to find a "Pinned Notes" category or somewhere where they can be found.
Is this intended or do you still need to fully implement the pinning feature?
Again, I'm on Manjaro Gnome with Notejot built from source.

Thank you!

**Comment by lainsce** [comment]
Pinned notes are now in the same list as normal notes, they have a pin icon by their side.

**Comment by carallo** [comment]
Alright, it's actually what I thought was the intention. Thank you!
