### ISSUE TITLE
ElementaryOS

### ISSUE THREAD

**Issue by aliceemanueli** [lainsce/notejot#339]
Good morning!  This app is not available in the ElementaryOS App Store... Please bring it to ElementaryOS.  Why do we miss it!

**Comment by lainsce** [comment]
They require me to use granite and the elementary OS platform instead of what I'm using, it would break my app 100% to port it, effectively making me have to have a branch just for elementary… Sorry, but you can find it on FlatHub instead, and you have the guarantee of updates by doing so.

**Comment by jadeastar** [comment]
Pulling in #340
