### ISSUE TITLE
Opening Notejot while it is already running duplicates notes

### ISSUE THREAD

**Issue by aljelly** [lainsce/notejot#34]
Steps to reproduce:

1) Go to Applications, open Notejot and create 3 notes. Write some text in at least one of them.
2) Without closing Notejot, go to Applications and open Notejot again. You will now have 6 notes.
3) Open Notejot again with the same method. You now have 12 notes.

If you close every note after doing this and then run Notejot again, the 12 notes come back up.

This is on version 1.2.8.

**Comment by lainsce** [comment]
I'll fix it on the next release. :+1:

**Comment by lainsce** [comment]
Fixed in master/1.2.9, closing issue :+1:
