### ISSUE TITLE
Title Buttons Broken in elementaryOS/Pantheon

### ISSUE THREAD

**Issue by jadeastar** [lainsce/notejot#340]
The title buttons appear duplicated on elementaryOS.

Notejot 3.4.9 from Flathub
![Screenshot from 2021-12-13 09 48 48](https://user-images.githubusercontent.com/37665485/145844814-e0ead59b-73c6-4689-90c4-94357551f640.png)
![Screenshot from 2021-12-13 09 56 03](https://user-images.githubusercontent.com/37665485/145845038-391a6f6c-9259-4f7e-addc-4c730854c95a.png)

(working correctly)
![Screenshot from 2021-12-13 09 56 13](https://user-images.githubusercontent.com/37665485/145845037-c893f377-e52c-4a5e-be24-bda7eabef05f.png)

**Comment by jadeastar** [comment]
I am using the flatpak, this isn't an issue with other Libadwaita app like TextEditor or Commit (pictured)
![Screenshot from 2021-12-13 14 52 16](https://user-images.githubusercontent.com/37665485/145886997-49cda170-301f-4beb-a5a2-5731e8f183e0.png)
![Screenshot from 2021-12-13 14 52 37](https://user-images.githubusercontent.com/37665485/145887038-cc8f7ac5-808a-4eb8-baf7-3ccd428a6781.png)

**Comment by lainsce** [comment]
I'll look into this; for what's worth, those apps have one titlebar while Notejot has multiple.

**Comment by jadeastar** [comment]
Thanks! I think it's super interesting how you use multiple titlebars

**Comment by dominichayesferen** [comment]
Unrelated, but on the plus side, you should definitely feel better in the regard that at least your application can actually support the weird layout somewhat before the changes were made (if not support them better now after changes)... unlike a certain famous web browser built by a massive company.

**Comment by lainsce** [comment]
The thing is, Linux is still a small marketshare, so they don't care if it's broken, Windows users are their priority, but anyways, issue's fixed (I hope) and closed.
