### ISSUE TITLE
[Feature Request] See notes contained into a notebook

### ISSUE THREAD

**Issue by diegstroyer** [lainsce/notejot#345]
I don't know if it's a feature included or not, have no sense of creating notebooks if you can't just view the notes included into?

Only option is in view is "All notes".

I supose that, when I click over one Notebook, I only wanna see the notes contained into it.

But click over Notebook does nothing.

Thanks, your app looks really nice.

**Comment by lainsce** [comment]
This is a feature that I'm researching how to do.

**Comment by lainsce** [comment]
Fixed in main, next release will have it! :heart:
