### ISSUE TITLE
Window buttons are displayed multiple times when left side positioning is enabled

### ISSUE THREAD

**Issue by vsv** [lainsce/notejot#347]
I have set up the window buttons to be displayed on the left side:
```
$ gsettings get org.gnome.desktop.wm.preferences button-layout
'close,minimize,maximize:icon'
```
With this setting, the window buttons are displayed multiple times:
![image](https://user-images.githubusercontent.com/94895976/148142975-de3bcbb9-5a98-44d7-861e-953bd299db82.png)

Version: 3.3.3 (Flatpak)

**Comment by lainsce** [comment]
This is fixed, will come in next version.
