### ISSUE TITLE
Can't open notes on mobile layout

### ISSUE THREAD

**Issue by Deissson** [lainsce/notejot#348]
I Can't open notes on mobile layout (Minimized to be like one)                              

Applies to version 3.3.3

[here's a video of demonstrating the bug ](https://youtu.be/KVbz2FYOPWI)

> How to reproduce bug:

1. enter a note
2. exit a note

> Result:

You cant enter a note 
________________________________________________

> How to **Temporarily** fix: 

As shown in the [video](https://youtu.be/KVbz2FYOPWI),
You need to enter another note (or create one)
then enter a note that you tried to enter

**Comment by lainsce** [comment]
This is a known bug, will be fixed on the next version.
