### ISSUE TITLE
can't enable dark mode

### ISSUE THREAD

**Issue by cobalt2727** [lainsce/notejot#354]
> There is a small tool made by exalm that they use for testing the mode change, you could compile that and use it. Pop!_OS won't upgrade to GNOME 42 because of off-topic drama.

_Originally posted by @lainsce in https://github.com/lainsce/notejot/issues/244#issuecomment-1012727338_

What can we use for this? I couldn't find anything that jumped out to me after a quick look at exalm's GitHub.

**Comment by oscfdezdz** [comment]
Check [this](https://gitlab.gnome.org/exalm/color-scheme-simulator) out.

**Comment by cobalt2727** [comment]
I ran the commands in the README as stated and Notejot is still in light mode - do I have to build the GUI too?
```css
meson build --prefix=/usr -Dgui=false
cd build
ninja
sudo ninja install
systemctl --user restart xdg-desktop-portal
```

I should note that when building with `-Dgui=true` I got the following results:
```r
cobalt@cobalt-inspiron:~/color-scheme-simulator$ meson --reconfigure build --prefix=/usr -Dgui=true
The Meson build system
Version: 0.60.1
Source dir: /home/cobalt/color-scheme-simulator
Build dir: /home/cobalt/color-scheme-simulator/build
Build type: native build
Project name: impatience
Project version: 0.1.0
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0")
C linker for the host machine: cc ld.bfd 2.37
Vala compiler for the host machine: valac (valac 0.52.6)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Dependency systemd found: YES 248 (cached)
Configuring xdg-desktop-portal-impatience.service using configuration
Configuring org.freedesktop.impl.portal.desktop.Impatience.service using configuration
Dependency gio-2.0 found: YES 2.68.4 (cached)
Program build-aux/meson/postinstall.py found: YES (/home/cobalt/color-scheme-simulator/portal/build-aux/meson/postinstall.py)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Dependency gio-2.0 found: YES 2.68.4 (cached)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Found CMake: /usr/bin/cmake (3.18.4)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)

gui/src/meson.build:7:0: ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake

A full log can be found at /home/cobalt/color-scheme-simulator/build/meson-logs/meson-log.txt
```
Would running `sudo apt install libgtk-4*` be what I'm looking for?

**Comment by lainsce** [comment]
Yes to both questions. Although, I don't know how the gtk4 developer pkg is name in Ubuntu/Pop, so search it up before installing unnecessary stuff. :)

**Comment by cobalt2727** [comment]
I got GTK4 installed but it seems like I'm at a dead end with Ubuntu until 22.04 rolls around or something.
```bash
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gtk4 found: YES 4.4.0
Found CMake: /usr/bin/cmake (3.18.4)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libadwaita-1 found: NO (tried pkgconfig and cmake)

gui/src/meson.build:7:0: ERROR: Dependency "libadwaita-1" not found, tried pkgconfig and cmake
```
The only `libadwaita` packages in the repo are `libadwaitaqt1`, `libadwaitaqt-dev`, and `libadwaitaqtpriv1`, none of which resolved the error. ~~I should look into switching to Fedora or Arch or something...~~

I'll just stick with Gnome's ToDo app for the time being since that's still on GTK3 - thanks for the help though!
