### ISSUE TITLE
[Feature Request] Select multiple notes in list

### ISSUE THREAD

**Issue by janopae** [lainsce/notejot#358]
It would be nice if the notes list allowed multiple selections. This of course needs a design for the edit view – I propose replacing the edit view with a placeholder text that says how many notes are selected when multiple notes are selected.

The options "Move note to a notebook", "Pin/unpin note", changing the colour and "delete note" from the menu could then be performed simultaneously on multiple notes.

**Comment by lainsce** [comment]
Good idea, but will require a lot of work for holding selections and all the states that this would imply in the backend.

**Comment by lainsce** [comment]
I've decided that these operations don't make sense with the simplicity of Notejot; where if you want to edit notes it's a purposeful action on the note you are doing it to, to not simply do things for multiple notes without checking them first to really decide if the user wants to do that action to that note. Closing.
