### ISSUE TITLE
Suggestion for improvement of icon choice and layout

### ISSUE THREAD

**Issue by Heiko-M** [lainsce/notejot#36]
I have two suggestions about the icons in the top bar of each note:

1. The gear icon currently has only one function, changing the note's color. This, however, is not evident from the gear symbol. I would suggest changing it into a brush symbol for example.

2. To me it feels like the three icons should be grouped together and placed at the top right in the following order: New note (plus icon) - change color (brush icon) - delete note (trash can icon). In that way, the order of the icons would represent the lifecycle of a note: creating it, coloring it and deleting it if not needed anymore. It feels like they belong together (I would understand if you opted for leaving the 'new note' icon on the left, in that case, however, I would still swap the positions of the two icons on the right side).

Those are just two improvements that came to my mind while using your app. I hope you agree and we will see those changes in the next version :)
Cheers!

**Comment by lainsce** [comment]
I think it's better if I did this: the gear menu has all items inside it: Add note, change color (as submenu maybe), delete note. Does that sound better?

**Comment by Heiko-M** [comment]
I think it depends on your future plans with the app. If you are planning to add more features, pooling them under the gear menu would make sense and keep the header clutter-free. In that case, a color picker like in the context menu of files would be rad! However, with just the three actions present, I prefer having them right at my finger tips instead of hidden in a menu. I also think 'new note' and 'delete note' are central actions in your app and they should, therefore, be just one click away.
It would be awesome to get an opinion on this from someone of the elementary design team...

**Comment by lainsce** [comment]
I feel like making that Files' color picker is a great idea: Text isn't universal, colors are, so grepping them would be easier both for maintaining AND for translator overwork, since now they don't need to translate color names.

**Comment by lainsce** [comment]
I think this bug is now fixed, try out the new AppMenu :smile:

**Comment by eljefuri** [comment]
I just duplicated one aspect of this [here](https://github.com/lainsce/notejot/issues/97) apparently. It is an issue again because all of the functionality described has moved _outside_ of the gear menu.

**Comment by lainsce** [comment]
I've answered you there.
