### ISSUE TITLE
[Feature Request] Drag & Drop support for notes

### ISSUE THREAD

**Issue by janopae** [lainsce/notejot#360]
It would be nice if the notes could be dragged onto notebooks to move them or onto the trash to delete them.

**Comment by lainsce** [comment]
If only drag and drop on GTK4 wasn't so puzzling to use. I still don't know how it works.

**Comment by lainsce** [comment]
Due to the complexity of these drag operations, and GTK4 drag and drop being difficult to understand for widgets, I have decided to not support drag and drop. Once drag and drop is more well documented and known for widgets, I will implement it.
