### ISSUE TITLE
New notes appear in a random position in the list

### ISSUE THREAD

**Issue by carallo** [lainsce/notejot#362]
Hi @lainsce!
Lately I'm having a weird issue. When I open a new note it appears (apparently) randomly in a position in the middle of the notes list. Ideally they should appear on top of the list, being listed in latest edit order.
Is this intended?

**Comment by lainsce** [comment]
Could you do a screencast with Kooha so I see what's happening? :)

**Comment by lainsce** [comment]
The pattern is really this:

1. Pinned
2. Recent
3. Others

So it's not random, it just looks like it. Check the dates on notes. :)

As for clicking on a note changes its last modified time, this was brought up as something needed by a GNOME team's designer, so I'm trusting them.

**Comment by carallo** [comment]
> The pattern is really this:
> 
>     1. Recent
> 
>     2. Others
> 
> 
> So it's not random, it just looks like it. Check the dates on notes. :)
> 
> As for clicking on a note changes its last modified time, this was brought up as something needed by a GNOME team's designer, so I'm trusting them.

Mhh the last modified time thing is a bit weird to me, doesn't feel really right. If I want to simply read a note it shouldn't appear as recently edited and come up on top of the list. But if it doesn't depend from you...

The pattern anyway doesn't seem working right. If watch the video the first note has been edited in January while under it there are others which have been edited later. And it was not a pinned note either (even though pinned ones do not go on top anyway)... 🤔

**Comment by lainsce** [comment]
I'm going to look into the ordering of notes and see if there's something awry.

**Comment by carallo** [comment]
> I'm going to look into the ordering of notes and see if there's something awry.

Thank you! And sorry for being annyoing 😅

**Comment by lainsce** [comment]
> > I'm going to look into the ordering of notes and see if there's something awry.
> 
> Thank you! And sorry for being annyoing sweat_smile

Nah, you actually unearthed a bug. It's all wrong from what I saw in code lmao

**Comment by carallo** [comment]
> Nah, you actually unearthed a bug. It's all wrong from what I saw in code lmao

Ahah then I'm happy to have helped 😝

**Comment by lainsce** [comment]
Fixed! :heart:

**Comment by carallo** [comment]
Thank you so much! I will check as soon as I can :)

**Comment by lainsce** [comment]
It's still in only this repo as I am making the next release's things.
