### ISSUE TITLE
[Bug] Unordered List making doesn't work on multi-lined selections

### ISSUE THREAD

**Issue by oyajun** [lainsce/notejot#364]
I can't make selected multiple line text into unordered list now If I click unordered list button.
![image](https://user-images.githubusercontent.com/81346541/154809720-c23df4a0-c72c-46eb-aec8-0c46a1e1daa9.png)

I can do it on GitHub's Mark Down Editor. 
![image](https://user-images.githubusercontent.com/81346541/154809779-0f76e11b-5f38-4751-997a-7d6b3c136cc7.png)

And please support Number List.

**Comment by lainsce** [comment]
メッセージが理解されることを願っています。

順序なしリストは、写真にあるGNOMEで見られるような、既存のダッシュがない場合に機能します。
番号付きリストについては、新しいissueを開いてください。

**Comment by oyajun** [comment]
Thank you for reply in Japanese.
I am not good at English and I can't tell you about problem well.
Sorry💦

**Comment by lainsce** [comment]
Fixed :heart:

**Comment by lainsce** [comment]
Numbered list will come later, not on this release.
