### ISSUE TITLE
[Enhancement] Instantly open a newly created note

### ISSUE THREAD

**Issue by martin-desktops** [lainsce/notejot#366]
From what I have observed, newly created notes are added to the notebook, but the user has additionally click on the proper position from the notes list and then focus on text box, remove  placeholder text and finally start noting. I think that we can reduce some unnecessary steps.

My proposition - User clicks on "Add Note" and then: the newly created note instantly opens up, it focuses on text input box and when user starts typing,  placeholder is removed.

**Comment by lainsce** [comment]
Looking back at this, it goes against what I want to make for the next release, because there will be two visual modes of accessing the notes, so adding a notes can't be relied upon to always open the note editing part of the UI.
