### ISSUE TITLE
Dialog backdrop not clearing after being closed

### ISSUE THREAD

**Issue by letops** [lainsce/notejot#369]
### Description
I am unsure of how to describe it in further detail, but basically when opening the dialog for moving a note to a notebook, the backdrop doesn't clear after the dialog closes. The backdrops are "stackable", so the app keeps getting darker and darker, but it doesn't prevent me from clicking any button. This is the only dialog where this issue happens and I've tried other dialogs and buttons to see if something fixes it. Only closing and opening the app seems to fix the issue.

### Version
3.5.0 - Mar 29, 2022

### OS
Elementary OS - 6.1 Jòlnir (Ubuntu 20.04)

### Video
Recorded on Peek, as no keys are pressed

[Video](https://user-images.githubusercontent.com/9222108/163498504-57a883b4-e633-43eb-b198-50bbe2faee0e.mp4)

**Comment by lainsce** [comment]
I couldn't make this happen locally, must be some elementary OS bug. Try making an issue in their bug tracker about what could this backdrop bug be.
