### ISSUE TITLE
Click note title to rename

### ISSUE THREAD

**Issue by danrabbit** [lainsce/notejot#37]
It would be nice to be able to give a note a name by clicking the title to edit ("Notejot" by default)

Photos has a decent widget here for going between a label and an entry:
![ezgif-5-0defe6a219](https://user-images.githubusercontent.com/7277719/32408460-64518240-c155-11e7-9502-014d50b554ac.gif)

**Comment by lainsce** [comment]
I see! I'll implement it! :+1:

**Comment by lainsce** [comment]
Fixed in 1.3.0, closing~
