### ISSUE TITLE
[Bug] No back button when folding in Trash List view

### ISSUE THREAD

**Issue by tronta** [lainsce/notejot#370]
When shrinking the window with the bin selected, no back button appears. See attached screen cast.
Version 3.5.0

https://user-images.githubusercontent.com/5135577/163688704-8396b050-3b34-4acc-bb13-af5900bf9df7.mp4

**Comment by lainsce** [comment]
I can't see the attached screencast.

**Comment by tronta** [comment]
one moment, I'm still struggling with attaching one in an accepted format.

**Comment by tronta** [comment]
can you see this?
https://user-images.githubusercontent.com/5135577/163688475-99924bcb-7a98-43ce-b7e1-3682809fe8d3.mov

**Comment by tronta** [comment]
Not sure what the problem is, Firefox displays only the second half and Chrome does not show it at all. Does it work, when you download the video?

**Comment by lainsce** [comment]
Ah, I could see it now by downloading; this must be a bug with the back button not showing in that specific view. Will fix it for next release.

**Comment by tronta** [comment]
cool. Thanks

**Comment by lainsce** [comment]
Fixed, will be in the next release.
