### ISSUE TITLE
[Bug] Text between two pairs of syntax tokens gets formatted as well

### ISSUE THREAD

**Issue by fieraoh** [lainsce/notejot#371]
State what version you're using: 3.5.1

https://user-images.githubusercontent.com/72320316/164179740-910618a7-2649-4f79-8a75-b1dde34f8ced.mov

**Comment by lainsce** [comment]
It's treating what's between the inner \*\* as bold text as well... Hm..

**Comment by lainsce** [comment]
Fixed
