### ISSUE TITLE
[Bug] Selecting a note in Note Grid then changing view breaks the UI

### ISSUE THREAD

**Issue by daved3464** [lainsce/notejot#372]
Notejot v3.5.1

the app becomes unusable after opening a note in app grid and then going to any other view. 
Main section goes blank like if that section of UI crashed, can't use the main view, select notes, add new note button does not appear.

https://user-images.githubusercontent.com/7122738/164538308-f01a88c3-6137-48ac-a30e-a7d3497dc3f4.mp4

**Comment by lainsce** [comment]
Yeah, when you open a note in the grid, the back button should go back to the grid and restore the UI... It's something I still have to fix because this UI is not what I planned to use, but had to just to meet the dev cycle.

**Comment by daved3464** [comment]
Mind if I fill some issues on general UX and stuff I've found by using the app?

**Comment by lainsce** [comment]
I don't mind, the more issues posted the better the app will be. :)

**Comment by lainsce** [comment]
Fixed
