### ISSUE TITLE
When highlight text and drag off window, scrolling does not follow

### ISSUE THREAD

**Issue by admun** [lainsce/notejot#378]
When I try to highlight text, and drag to the edge of window, scrolling did not happened.

Usually, the highlight will follow as cursor move off the window. 

Is there way to enable that?

**Comment by admun** [comment]
version = 41.5, on Fedora 34, install from software via flathub

**Comment by lainsce** [comment]
This doesn't seem to be a thing I can enable with GTK4.

**Comment by admun** [comment]
[Screencast from 05-12-2022 08:50:54 AM.zip](https://github.com/lainsce/notejot/files/8680731/Screencast.from.05-12-2022.08.50.54.AM.zip)

**Comment by admun** [comment]
In the screencast, I highlight text and drag the cursor to the bottom of the screen, and scrolling start and following until the bottom of the page.

**Comment by admun** [comment]
@lainsce I found another way to show this issue.

1. click on a beginning on a line in the app's not area
2. using shift-down arrow to highlight the line and move the cursor to next line
3. continue to do that until it reach the bottom of the note text area, and continue to shift-down arrow

You will found that the pane will not move and follow the cursor with highlight text, and move off the visible area. When you use the mouse to scroll down, you will see the text outside of the visible area are highlight.

I think that's a part of problem at hand.

Hope this help you identiy the issue and a fix.

**Comment by lainsce** [comment]
Let me ask again:

This doesn't seem to be a thing I can enable with GTK4.
Can you show me an example of an app having this functionality?

**Comment by mkblast** [comment]
> Let me ask again:
> 
> This doesn't seem to be a thing I can enable with GTK4. Can you show me an example of an app having this functionality?

Idk if this counts, but when using the Text Editor app it's functions just like the issue mentioned.

I can't upload a video to show it because github dont support the file format that new gnome screen-cast tool uses.

**Comment by lainsce** [comment]
Text Editor uses a different widget for the text area. Maybe it could only be enabled there? idk.

**Comment by mkblast** [comment]
> Text Editor uses a different widget for the text area. Maybe it could only be enabled there? idk.

I took a look the other note taking apps like paper, they use the same widget as Text Editor.

Idk how your are work, but can't you use the same widget?
