### ISSUE TITLE
[Feedback] A collection of feedback about the UX and UI

### ISSUE THREAD

**Issue by Miqueas** [lainsce/notejot#379]
__Notejot version__: 3.5.1 (Flatpak)

## The problems

I recently installed Notejot on my laptop and being the first time I use it, it left me a bit confused for 2 main reasons:

  1. I expected that, after creating a new notebook and selecting it, if I created a new note, it would appear in the "active" notebook
  2. Moving a note to a notebook is not very intuitive in the sense that the option to do so is inside a menu and not in a more visible place

Honestly, after that experience, I simply never opened the app again. At first glance, to me, it seemed like:

  - Or the application had a bug
  - Or it was simply poorly made

And I clarify that with the latter I don't mean to attack the developer, it was simply the impression I had. Anyway, today I reopened the app to record video of what I'm talking about and share it with the developer and I noticed other things:

  - The way notes are erased is tedious
  - In the grid view, when new notes are added, they look like long "strips" (which honestly seems a bit "out of place" to me).

## Suggestions that I think may help

> 1. I expected that, after creating a new notebook and selecting it, if I created a new note, it would appear in the "active" notebook

Well, this one is easy: the application should have the expected behavior. That is, that the notes are added to the selected notebook, instead of having to move them manually.

> 2. Moving a note to a notebook is not very intuitive in the sense that the option to do so is inside a menu and not in a more visible place

Either by allowing you to change it from here:

![image](https://user-images.githubusercontent.com/31262466/167765709-d5ff72e6-d952-4855-99f8-76b22b1c21ef.png)

Or by adding an additional button here:

![image](https://user-images.githubusercontent.com/31262466/167765812-6f5ebba2-08ee-4c83-8e0d-1a8f7ef1fcbd.png)

I think they could solve it.

> - The way notes are erased is tedious

As I said just above, I think adding a button in this area can work:

![image](https://user-images.githubusercontent.com/31262466/167765812-6f5ebba2-08ee-4c83-8e0d-1a8f7ef1fcbd.png)

> - In the grid view, when new notes are added, they look like long "strips" (which honestly seems a bit "out of place" to me).

I think that, if it is simply square or rectangular in shape, it is fine.

## Resources

Here is the video I shared with the developer

https://user-images.githubusercontent.com/31262466/167766614-fd5ad1bc-19d0-4ca4-b626-fa820d90d5d5.mp4

**Comment by Miqueas** [comment]
Also, I believe that all the options that are in this menu can be moved to the header bar area

![image](https://user-images.githubusercontent.com/31262466/167768903-c355ed28-1880-42b2-b66c-4ddb6e47a8cd.png)

In the case of colors, they could still be kept inside a menu, to avoid filling the header bar with too many elements.

**Comment by Miqueas** [comment]
Interesting 👀

**Comment by lainsce** [comment]
There are still somne stuff missing like creating a note inside the active notebook, but for now 90% of the issue is done

**Comment by Miqueas** [comment]
> There are still some stuff missing like creating a note inside the active notebook, but for now 90% of the issue is done

Damn 🔥
