### ISSUE TITLE
Show title of notes in dock

### ISSUE THREAD

**Issue by fegue** [lainsce/notejot#38]
Expected behavior:
Multiple notes are open and were given different titles.
Right clicking on the Notejot icon in the dock shows the different titles.
We can thus quickly select a note.

Actual behavior:
A right click on the icon shows the Reversed Domain Name Notation as many times as there are notes.
We don't know which note to select (and it looks somewhat unpolished).

Tested on version 1.3.0

![notejot_context-menu](https://user-images.githubusercontent.com/19360071/32457959-041dd0fe-c32b-11e7-9b26-6e654ae8a7dc.png)

**Comment by lainsce** [comment]
I'll fix it for the next release, sit tight :wink:

**Comment by fegue** [comment]
Good work, thank you!
