### ISSUE TITLE
Background gradient in dark mode are so not smooth, In light mode is nearly invisible

### ISSUE THREAD

**Issue by daudix-UFO** [lainsce/notejot#382]
**In "real" it looks pretty much same**

![Снимок экрана от 2022-05-29 00-46-31](https://user-images.githubusercontent.com/77155297/170843821-8a258ab5-03a2-4d47-872e-945bbcfa82e4.png)
![Снимок экрана от 2022-05-29 00-46-41](https://user-images.githubusercontent.com/77155297/170843824-b885d005-0bef-4c80-b032-f830e56620d3.png)

**Comment by lainsce** [comment]
This is out of scope of the project, this is a GTK4 thing.
