### ISSUE TITLE
Making notes in one of the notebooks can't enter on the selected notebook

### ISSUE THREAD

**Issue by aldiwira** [lainsce/notejot#386]
- Issue
I'm trying to make a note in the notebook that I select in the notebooks menu. but the notes I made can't be listed in my notebooks. but I try to enter all the menus, the notes I made are on those menus

- Notejote Version
Notejote 3.5.

- Record from my computer

https://user-images.githubusercontent.com/48662152/172794233-fa44b1f0-ea5d-4cd0-9a75-894152d776cb.mp4

**Comment by lainsce** [comment]
Right now, making a note is generic, and won't auto-add a notebook if one is selected; this will be a thing in the next version.

**Comment by lainsce** [comment]
Due to the change in the UX of notebooks, this is invalid now, as Notebooks are more of a search filter now, and can be easily added to a note due to a prominent button.
