### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by zoncrd** [lainsce/notejot#39]
Notejot version 1.3.0 works in a very strange way as you can see in this video
[Screencast_video.zip](https://github.com/lainsce/notejot/files/1459335/Screencast_video.zip)

**Comment by lainsce** [comment]
Yeah, that's not strange, it's just a small bug waiting to be crushed by me lol.
Expect a fix in the next release (I'm already with a release queued though).

**Comment by lainsce** [comment]
Fixed in master, will appear in the next release!

**Comment by worldofpeace** [comment]
I was just about to file a report for this. It's been annoying me for weeks! Glad to see it fixed. :+1:
