### ISSUE TITLE
"Unordered List" icon is missing

### ISSUE THREAD

**Issue by electricduck** [lainsce/notejot#390]
![image](https://user-images.githubusercontent.com/1594644/192068333-deb8974a-c73a-42dd-9900-175bd8a147a0.png)

Ever since installing Notejot, the "Unordered List" icon in the note toolbar has never worked properly.

Currently on Notejot 3.5.1 from the Flatpak version, on Fedora 35. This seems to be some sort of odd environment issue as I've not seen the issue crop up before, and it's weird it should be happening at all since these icons &mdash; correct me if I'm wrong &mdash; are coming from the Flatpak runtime

**Comment by lainsce** [comment]
It looks as if you changed the icon theme; that will also change which icons are present.

**Comment by electricduck** [comment]
Hm, I _am_ mistaken then. Was led to believe libadwaita applications always used the Adwaita icon theme too.
