### ISSUE TITLE
Add list/checklist functionality

### ISSUE THREAD

**Issue by calhix** [lainsce/notejot#391]
I gotta say I love this app, been using it for a long while now and it has only gotten better, plus it works perfectly on Asahi Linux and PinePhone. I would greatly appreciate the ability to make lists/checklists as well, it would be nice to be able to sync them between devices like for grocery lists between family members or whatever else in real-time.

Edit: I see now there's a button to make selected text into an unordered list. I was thinking something like how Notally on F-Droid does it. You have the option to make a new note or new checklist with checkboxes when you complete a task.

**Comment by lainsce** [comment]
I feel like this is a bit of a feature creep for Notejot; checklists suit more an app that's for tasks and task-oriented usage. Notejot is more for quick organizable notes.

**Comment by calhix** [comment]
Well since you have a button to make a checklist already within a note, perhaps you can add the functionality of checkboxes instead of just the dashes? Or a way to quickly dismiss a task?
-------- Original Message --------

**Comment by lainsce** [comment]
To draw a checkbox I'd need to inject a Gtk.RadioButton to display it, so not an easy task when the TextView is for just text and not widgets, plus how to save this.

**Comment by lainsce** [comment]
I have an idea, I will make a section in the app to add checklist items in a sort of To-Do mega list that shows only in that section, like I do for Notes. Would that help achieve what you wanted with checkboxes?

**Comment by lainsce** [comment]
Landing Task list function, technically fixes this bug so closing.
