### ISSUE TITLE
Update to GNOME Runtime version 44

### ISSUE THREAD

**Issue by vixalien** [lainsce/notejot#394]
When updating the app on flatpak, the CLI gives this warning:

```
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.lainsce.Notejot
```

**Comment by lainsce** [comment]
Yes, however since Notejot's next release won't be using a GNOME runtime anymore, this issue isn't going to be fixed. Expect a release with the tauOS runtime.

**Comment by vixalien** [comment]
hmm interesting. why will the next notejot use the tauos runtime?

it seems like tauos is a gnome based distro so I'm assuming it's runtime includes the gnome runtime.

what does the tauos runtime add?

**Comment by lainsce** [comment]
It adds some features that the GNOME one doesn't provide. You'll see them once tauOS releases.
