### ISSUE TITLE
Troubles Building on Manjaro - can't find libhelium-1 and libbismuth-1

### ISSUE THREAD

**Issue by jacobmealey** [lainsce/notejot#398]
As the title says I am having trouble building `main` on Manjaro. Meson reports the following:
```
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libhelium-1 found: NO (tried pkgconfig and cmake)

../meson.build:90:0: ERROR: Dependency "libhelium-1" not found, tried pkgconfig and cmake
```
I thought I might just be able to install libhelium but there isn't a package with that title in the repositories. When I went digging more I found a few different projects called libhelium so I wasn't sure which to pick. The case for libbismuth is the same. 

If anyone can provide insight it would be appreciated, it's probably something silly I am looking over!

**Comment by SymeonKasidis** [comment]
Both libhelium and libbismuth seem to be frameworks or libraries for TauOS  and under development. you can try and compile them yourself. I havent tested it yet but given that is under development things will definately break. https://github.com/tau-OS

**Comment by lainsce** [comment]
Long story short, Notejot is now a tauOS app. So those two libraries are from that OS. 😛

**Comment by xiota** [comment]
libhelium: https://github.com/tau-OS/libhelium

libbismuth: https://github.com/tau-OS/libbismuth
