### ISSUE TITLE
notejot and libhelium-1

### ISSUE THREAD

**Issue by kloczek** [lainsce/notejot#399]
https://github.com/lainsce/notejot/blob/f415267f4aec9cef4d0f203fcc46cd00e4bf098e/meson.build#L96

Looks like libhelium is no longer maintained since 2018 https://github.com/novalabsxyz/libhelium 🤔

**Comment by lainsce** [comment]
It's another libhelium than that. Long story short, Notejot is now a tauOS app. So expect a new release when that OS releases. 😛

**Comment by kloczek** [comment]
So where is this libhelium? 🤔

**Comment by xiota** [comment]
https://github.com/tau-OS/libhelium
