### ISSUE TITLE
Update Flatpak runtime

### ISSUE THREAD

**Issue by Miqueas** [lainsce/notejot#401]
__Not exactly an issue! Just commenting :)__

![image](https://user-images.githubusercontent.com/31262466/236888041-227eb9ec-3137-4137-8018-24fa3a904d93.png)

**Comment by Miqueas** [comment]
> settings runtime to 43 gives this error

Damn what, that's weird :thinking:

**Comment by Miqueas** [comment]
Oh wait, I see what's the problem and it's supposed to be fixed already #395

**Comment by lainsce** [comment]
Yeah it's fixed already. :P
Closing the issue.

**Comment by Miqueas** [comment]
Oh, epic
