### ISSUE TITLE
Still having data loss issue (tested with master)

### ISSUE THREAD

**Issue by arshubham** [lainsce/notejot#44]
Still having data loss issue on master (Tested after a reboot). 

[See Video ](https://youtu.be/B7_2owLuJA4)  --> Happens after two tries to reproduce the bug

Not in every time but it happens as:
1. Create 2 notes
2. Close 1 note .
3. Click on the icon from slingshot .
4. Close other note.
5. Open notejot again from slingshot. The first note will be empty but title and color is remembered.

Thanks!

**Comment by lainsce** [comment]
Yeah, I don't think this will be possible to fix in one release, sit tight with it, and in the next Friday release, I'll be fighting to fix this issue.

**Comment by arshubham** [comment]
> but the ones you've closed are saved for the next session
So shouldn't they retain the text?  The title does.

**Comment by lainsce** [comment]
You can see in your own video, that they do retain text there until the end of the video, where I'm confused as to how it lost the text.

**Comment by arshubham** [comment]
Yeah sorry I wasn't more clear. While making the video it only happened on third attempt I don't know why.  But can also happens sometimes on first or second.  Maybe you can add some debug messages in  the code to see what is going wrong here.

**Comment by lainsce** [comment]
I think I know where the bug is, it's when you close the note which is the first note opened before closing the others.

**Comment by lainsce** [comment]
I've been testing this, and it isn't because of my earlier comment. It's actually some finicky order of operations that you've found, and I can't reproduce without actually forcing it. I'll close this issue since most users will not find it on their usage unless they actually force the app to behave badly.
