### ISSUE TITLE
Basic Markdown Support

### ISSUE THREAD

**Issue by mnavarrocarter** [lainsce/notejot#46]
I love this app! It's easily one of my favorite apps on Elementary AppCenter. There's just one feature that I miss, and that is the possibility to add some basic markdown to my notes: bold, italics, lists and things of sort.

I know that maybe this will be a lot of effort to implement, because you'll probably have to implement view modes (edit or preview) in the notes view, and then the renderer.

So, just leaving this feature request here if you would like to implement it. If not, still a great app!

**Comment by lainsce** [comment]
I don't think a simple sticky notes app needs markdown to be honest, and even then, there's Quilter from myself that does exactly what you're describing here. 😄
