### ISSUE TITLE
contents 2 of my 3 notes disappeard

### ISSUE THREAD

**Issue by js-d-coder** [lainsce/notejot#50]
Hi,  
Thanks for this app, very useful  
I am using latest version of this app for my everyday use.  
After last reboot 2 of 3 notes got deleted. It only shows window and not the content.  
I don't know how can I provide more information, please let me know how can I.  
Thanks!

**Comment by lainsce** [comment]
If you didn't read my tweet about saving the notes contents before upgrading, you might have been hit with the new backend overwriting the file.
