### ISSUE TITLE
No selection highlights in title

### ISSUE THREAD

**Issue by peteruithoven** [lainsce/notejot#63]
When editing the title there is no indication of what's selected. Usually the selected characters get a inversed color and  background color. 

Example 1:
1. Create new note
2. Click in title (a bottom border appears)
3. Press ctrl + A

Expected: A dark background behind text
What happens: No visual change, no selection indication

Example 2:
1. Create new note
2. Click in title (a bottom border appears)
3. Press right key (a cursor appears)
4. Press Shift + left key

Expected: A dark background behind part of the text
What happens: No visual change, no selection indication

**Comment by lainsce** [comment]
I'll see what I can do when I'm able to.

**Comment by lainsce** [comment]
I've tested this in Loki, and the title sure highlights... Are you in the last version released?

**Comment by lainsce** [comment]
Closing issue as it's not an issue anymore.
