### ISSUE TITLE
Graphical issues

### ISSUE THREAD

**Issue by hfel** [lainsce/notejot#67]
Hey! I seem to get weird graphical defects, such as a black line at the top window border and the stretched color bubbles.

![captura de pantalla de 2018-04-09 19-58-03](https://user-images.githubusercontent.com/16854594/38514416-6b6c00bc-3c31-11e8-9bba-b76523630b76.png)

I'm running GNOME version 3.28.0 on Antergos and using an external display.

**Comment by lainsce** [comment]
I have nothing to say but this is why Flatpakking takes time. My apps are designed around the elementary GTK theme, and so, you _will_ get graphical glitches on any other theme. I can't fix this.
