### ISSUE TITLE
Somehow no colors...

### ISSUE THREAD

**Issue by kolorafa** [lainsce/notejot#68]
I can correctly switch colors, but the gui doesn't show any, all gray.

![screenshot_20180416_173946](https://user-images.githubusercontent.com/921517/38820551-850cf96e-419e-11e8-8ea6-024e593242be.png)

By the way :(
How to check what version it is? 

No window with: com.github.lainsce.notejot --about
Unknown option --version
Unknown option -v

flatpak showing:
com.github.lainsce.notejot/x86_64/stable             system,current

$ LANG=C flatpak info com.github.lainsce.notejot
Ref: app/com.github.lainsce.notejot/x86_64/stable
ID: com.github.lainsce.notejot
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID:
Date: 2018-02-22 15:08:30 +0000
Subject: Remove redundant bits (7beacdee)
Commit: 09804ca899c0e99ee4f458d4512a518b6a3c71ab92f8781fa07ad6965cc6dd08
Parent: 5c7383f5431196af99c374fc5c20f4f7b6b15a58b9d451046181a6e5f834595f
Location: /var/lib/flatpak/app/com.github.lainsce.notejot/x86_64/stable/09804ca899c0e99ee4f458d4512a518b6a3c71ab92f8781fa07ad6965cc6dd08
Installed size: 4.8 MB
Runtime: org.gnome.Platform/x86_64/3.26

**Comment by lainsce** [comment]
This is due to it being a flatpak, it needs the elementary flatpak theme installed to have colors.
