### ISSUE TITLE
Watch cache file during app operation for syncing outside

### ISSUE THREAD

**Issue by mwolff44** [lainsce/notejot#69]
Hello,
Is it possible to sync note with Nextcloud sever ?

Thanks!

**Comment by lainsce** [comment]
As long as NextCloud has a simple API to use, it can be done.

**Comment by peteruithoven** [comment]
It has a WebDAV system, so if Notejot uses regular files as source Nextcloud could sync them.

**Comment by lainsce** [comment]
Notejot currently writes its notes to a JSON file, would that hamper progress on a fix to this?

**Comment by peteruithoven** [comment]
I could try it, where is the file located? I didn't really get the `Environment.get_user_cache_dir ()` part.

**Comment by lainsce** [comment]
The file's at `$HOME/.cache/com.github.lainsce.notejot/saved_notes.json`.
`Environment.get_user_cache_dir ()`points to `$HOME/cache`. :man_scientist:

**Comment by lainsce** [comment]
It should already pick up on changes AFAIK, but I'll see what I can do

**Comment by lainsce** [comment]
Tested this extensively, and it will pick up changes externally if you re-open Notejot.

Remember: Notejot is just a "widget" app, as such, it shouldn't have complex sync capabilities other than if opened again it'll read from cache.

Closing issue.
