### ISSUE TITLE
Deletes a note after I closed one of the Notejot windows

### ISSUE THREAD

**Issue by js-d-coder** [lainsce/notejot#72]
* Deletes a note after I closed one of the Notejot windows
* At first I had a window of note. I created a second one and closed the other. On system restart I found the first note has no note content and second one does.
* Version 1.4.0
* 
![screenshot from 2018-06-19 11 40 05](https://user-images.githubusercontent.com/23054879/41579690-94cfd4ea-73b5-11e8-9b69-5ce6740a5f7a.png)
Thanks!

**Comment by lainsce** [comment]
If you close but not delete, it's as if there was still a note between all the notes in the cache file there.
I might have to disable the close button on Notejot, because in the menu there's already a Delete Note option.

**Comment by lainsce** [comment]
I've thought about this, and it's better if the close button in Notejot serves the purpose of the menu's Delete Note.

**Comment by lainsce** [comment]
Fixed in master

**Comment by biswaz** [comment]
This bug just deleted some of my mission critical information. This required immediate attention. Please release the fix in the elementary appstore asap

**Comment by js-d-coder** [comment]
@biswaz I have been bitten in situations like this many times. Once my database design was lost by a software called laverna, I spend 4 hours designing that database.
So I have just stopped trying any new apps from eOS' AppCenter altogether. I use old robust technology called text files formatted in markdown.

**Comment by biswaz** [comment]
I'm astonished why a fix is not yet releases yet even after 18 days. Imagine clueless folks who doesn't know even where to report the error. eOS has an audience of lower technical proficiency (this is only an anecdotal evidence), who might be completely let down with this kind of problems. 

@lainsce I don't have anything against you. Even the fact you're making this app available for free is commendable. My observations are about the state of FOSS solutions.

**Comment by lainsce** [comment]
I did send it to review for availability on AppCenter with the fix. I'm just awaiting their review, which to be honest will take time due to them being in GUADEC.

**Comment by Vercris** [comment]
Sorry but since then and until now there is no solution despite the fact that almost half a year has passed. I use deepin OS and actually this is the only stocky note that I like. If someone tells me how I can help

**Comment by lainsce** [comment]
Please update your Notejot.
