### ISSUE TITLE
insert emoji broken

### ISSUE THREAD

**Issue by torikulhabib** [lainsce/notejot#74]
## Hello! If you found an error in this app, follow this template:

* insert emoji
* insert emoji croped 
*juno
* 
![screenshot from 2018-07-19 06-46-25](https://user-images.githubusercontent.com/26135527/42913550-cfc6daae-8b1f-11e8-920a-1ed67ea65668.png)

Thanks!

**Comment by lainsce** [comment]
That's not my app's fault, it's the fault of the popup which isn't something I can change or build on.
