### ISSUE TITLE
Close setting menu when focus is out of the app

### ISSUE THREAD

**Issue by delmicio** [lainsce/notejot#76]
Thank you for this app.

1. Open a note.
2. Open the options menu by cliking on the gear icon at the right corner.
3. Focus off the app by clicking on firefox for example.
4. Go back to note.
5. Options menu is still opened.

This should behave the same as when opening the options menu and the clickin on the note. You can see the menu auto closes.

Hope it helps.

**Comment by lainsce** [comment]
This isn't a bug with my app, it should be about something Firefox does with focusing windows, maybe it forces other windows to stay as they are?

**Comment by delmicio** [comment]
Firefox was just an example. I'll try to record it for you.
