### ISSUE TITLE
Font without russian characters

### ISSUE THREAD

**Issue by d1moncom** [lainsce/notejot#81]
Please use international font. Or add font settings. Now I have a bad result for russian text.

![2018-09-27 16-16-59_](https://user-images.githubusercontent.com/20462581/46142601-ef32a700-c270-11e8-98f2-20095db4cb43.png)

Eos Juno Beta2, app last 1.4.7.

**Comment by lainsce** [comment]
I'll add russian letters to the existing font, or find one with them.

**Comment by ryonakano** [comment]
![screenshot from 2018-09-30 22-07-43](https://user-images.githubusercontent.com/26003928/46257937-56fd2200-c4fd-11e8-95a2-51700e6eb183.png)

Same with Japanese text.

Notejot 1.4.7, on Juno Beta2

**Comment by lainsce** [comment]
Guess I'll have to revert to a normal font.

**Comment by lainsce** [comment]
It's decided, I'll use a normal font in the next version.

**Comment by aftabnaveed** [comment]
Can we not use the font of our choice, I really like the previous font. It really looked hand written.
