### ISSUE TITLE
Change "gear" icon to rainbow/color wheel if only used for changing colors

### ISSUE THREAD

**Issue by eljefuri** [lainsce/notejot#97]
Assuming that the optionality underneath it will be constrained to color selection for a given notepad, I'd say that the gear icon is a bit of an awkward choice. How about a color wheel or a rainbow instead, to make it more obvious what the button is for?

**Comment by lainsce** [comment]
There's no "color wheel" symbolic icon, and I might use the menu for other stuff too.

**Comment by eljefuri** [comment]
Yes and at one point the symbol of the gear was not synonymous with "application preferences window" either. 😃 In all seriousness, the so-called symbolic icon for a color wheel probably _is_ a color wheel. Or pick a rainbow e.g. what is found in Luna's color selector:

![screenshot from 2018-11-10 21-26-37](https://user-images.githubusercontent.com/44387419/48302463-e8fe3e80-e52f-11e8-9212-ef58db374504.png)

That said, if you _might_ use the menu for other stuff, it _might_ make sense to keep it. But as it stands, that there is a color selector beneath the gear is totally non-obvious.

**Comment by lainsce** [comment]
Well as it stands, many people do know there's a color selection in the gear menu. It's intuitive because in elementary OS, what in Android and others you'd have the three-dot for extra settings, it has the gear.

**Comment by eljefuri** [comment]
Yes, Elementary has the ⚙ standardized _for application preferences_. Unsurprisingly, that is a button that I have observed 20/20 eOS users shy away from. Perhaps the iconography gives the impression of technical or complex things unnecessary to worry about except in extreme circumstances, _e.g. metaphorically mirroring the nature of a physical gear_.

This use of it is categorically not the same thing. Under this ⚙ is the color of a window, which is something that I would use constantly, very much unlike a preferences pane which is used rarely.

**Comment by lainsce** [comment]
So I'm expected to change the icon just because it just does colors, right? I fail to see the big picture here. I'm going to be stunting the menu's already recognizable use that is already being used by lots of users, just because currently it does colors. Is that right?

**Comment by eljefuri** [comment]
It's your application and you're not necessarily expected to do anything. I do ask you to consider it though. This something between a feature request and a bug report in my opinion. Not critical, but I believe you're harming your app's usability by not making this aspect more clear.

**Comment by lainsce** [comment]
Open your book, are you just wanting this to be resolved for you, or you really think all users will benefit with this? _All_ elementary OS apps use a gear icon to denote further settings; so if I deviate from that, I'd be going against the guidelines. Case closed.

**Comment by eljefuri** [comment]
Yes, I absolutely think that all users will benefit from this.

**Comment by robertsanseries** [comment]
I believe that notejot was created to follow the UI pattern of elementary OS, so the App should follow the features provided by the system. The current icon already has a specific and well-known meaning, the HIG itself already defines and guides this (https://elementary.io/en_en/docs/human-interface-guidelines#popovers). In addition to the own Apps of elementary OS follow the same pattern.

I think it should remain as it is to avoid confusing users. Waiting for a change / future orientation by the eOS team.

Consistency and use of standards generates "state of fluidity".

#FocusingIsAboutSayingNo

**Comment by eljefuri** [comment]
I completely agree that it should follow the UI pattern of Elementary. I do not agree that this the correct application of the pattern. As I have said above, the ⚙ is used for _global application-wide settings_, and in this case it is being used to configure a single option of a single window.

**Comment by eljefuri** [comment]
For what it may or may not be worth: I just found the color/font size setting in Terminal's ⚙ menu and thought "ah so maybe those guys were right!". But when I changed a setting, it affected _all_ windows.

**Comment by lainsce** [comment]
I'll just end this once and for all. The Gear menu is iconic and ubiquitous for "More settings here" in elementary. Since I don't want to expose all the color options in a weird way, or have it on an icon that I might only have in one release then revert again (:trollface: inducing UX), I deem this closed.
