### ISSUE TITLE
Applet mode?

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/notejot#98]
I've gotten used to the workflow of several "applet" style apps where they're always-on-bottom and on all workspaces. I don't know if that makes sense for all Notejot users, but a "pin" in the headerbar that sets those properties on the window could be interesting. That way I can pin a sticky to my desktop and switch workspaces and still have it there behind my open tasks.

**Comment by lainsce** [comment]
True, that's an interesting idea. Will see how to implement.

**Comment by lainsce** [comment]
Fixed in master~
